import * as E from './engine.js';
import {ATTRIBUTES,KEYWORDS,STATUSES,OPERATIONS,CARD_LIBRARY} from './catalog.js';
import {generateRule,evaluateRule,scoreBoard,describeRule} from './rules.js';
import * as G from './game.js';
import {LESSONS} from './tutorial.js';

const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const POS=['上','右','下','左','中'],TYPE={operation:'操作',attribute:'属性',keyword:'关键词',status:'状态'};
let session=null,mode='home',selected=-1,raise=1,dialog=null,inspectionMode=false,aiTimer=null,toastTimer=null,lesson=null,sound=false,ctx=null,animated=0,catalogFilter='all',catalogSearch='',catalogLimit=36;
const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);}catch{}},remove(k){try{localStorage.removeItem(k);}catch{}}};
const learned=()=>storage.get('mask-tutorial-v1')==='done';
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function tone(freq=350){if(!sound)return;try{ctx??=new (window.AudioContext||window.webkitAudioContext)();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*.65,ctx.currentTime+.09);gain.gain.setValueAtTime(.06,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.11);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.12);}catch{}}
function persist(){if(session)storage.set('mask-session-v1',JSON.stringify(session));}
function header(){return `<header class="topbar"><div class="brand">暗面<small>MASK TABLE / 0.1</small></div><nav class="topnav"><button class="small subtle" data-act="help">怎么玩</button><button class="small subtle" data-act="catalog">牌库</button><button class="small subtle" data-act="ruleLab">规则实验</button><button class="small subtle audio-toggle" data-act="sound" aria-label="${sound?'关闭':'开启'}音效">${sound?'♪':'静音'}</button><button class="small subtle" data-act="home">主菜单</button></nav></header>`;}
function miniBoard(board){return `<div class="mini-board">${board.cells.map((c,i)=>`<span aria-label="${POS[i]}${c.value}">${c.value}</span>`).join('')}</div>`;}
function shapeMini(targets=[]){const index=[-1,0,-1,3,4,1,-1,2,-1];return `<span class="shape-mini" aria-hidden="true">${index.map(i=>`<i class="${i>=0&&targets.includes(i)?'on':''}"></i>`).join('')}</span>`;}
function effectName(category,id){return ({attribute:ATTRIBUTES,keyword:KEYWORDS,status:STATUSES}[category]||[]).find(x=>x.id===id)?.name||id;}
function cardHTML(card,index,{action='select',active=false,disabled=false}={}){
 const targets=card.kind==='bet'?(card.predicate?.expression?.scope||[]):(card.targets||G.legalPlacements(card)[0]?.targets||[]);
 const symbol=card.kind==='attribute'?'◇':card.kind==='keyword'?'✦':card.kind==='status'?'◷':'↔';
 return `<button class="playing-card ${card.kind==='attribute'?'attr':card.kind} ${active?'selected':''}" data-act="${action}" data-index="${index}" ${disabled?'disabled':''} aria-label="${esc(card.name+'。'+card.description)}"><span class="card-type">${TYPE[card.kind]||'赌注'} / ${String(index+1).padStart(2,'0')}</span><span class="card-title">${esc(card.name)}</span><span class="card-sigil" aria-hidden="true"><span>${symbol}</span></span><span class="card-text">${esc(card.description)}</span><span class="card-footer"><span>${targets.length?'固定位置：'+targets.map(i=>POS[i]).join('、'):'按牌面固定位置'}</span>${shapeMini(targets)}</span></button>`;
}
function maskCardHTML(b,i,action='chooseMain'){return `<button class="playing-card mask-card" data-act="${action}" data-index="${i}"><span class="card-type">随机主牌 / ${String(i+1).padStart(2,'0')}</span><span class="card-title">五位蒙版</span>${miniBoard(b)}<span class="card-text">五格各自独立生成。选定后扣下，数字只有你知道。</span><span class="card-footer">点击选择这一张<span>Ⅰ—Ⅴ</span></span></button>`;}
function boardHTML(board,{owner=0,hidden=false,known=[],revision=0,scope=[],affected=[],previewBoard=null,lessonBoard=false}={}){
 if(!board)return '';
 return `<div class="board">${board.cells.map((c,i)=>{
  const fact=known[i],current=fact&&fact.revision===revision,historical=fact&&!current;
  const value=hidden?(current?fact.value:historical?fact.value+'?':'?'):c.value;
  const attrs=[c.attribute?effectName('attribute',c.attribute):'',...c.keywords.map(k=>effectName('keyword',k))].filter(Boolean);
  const statuses=Object.entries(c.statuses).map(([id,s])=>effectName('status',id)+s.turns);
  const before=previewBoard?.cells[i]?.value;
  const animation=session?.lastAnimation;const changed=!lessonBoard&&animation?.nonce===animated&&animation?.who===owner&&animation.targets.includes(i);
  const aria=hidden?(current?`${POS[i]}位，已查得${fact.value}`:historical?`${POS[i]}位，上次见到${fact.value}，目前未确认`:`对手${POS[i]}位，数字保密`):`${POS[i]}位，数字${c.value}${attrs.length?'，'+attrs.join('、'):''}`;
  return `<button class="slot ${hidden?'dark':''} ${current?'known':''} ${historical?'historical':''} ${affected.includes(i)?'affected':''} ${scope.includes(i)?'scope':''} ${changed?'changed':''}" data-act="${lessonBoard?'lessonCell':'cell'}" data-owner="${owner}" data-pos="${i}" aria-label="${esc(aria)}"><span class="position">${POS[i]}</span><span class="number">${esc(value)}</span>${historical?'<span class="knowledge-label">上次见 · 非当前确认</span>':''}<span class="tags">${esc(attrs.slice(0,2).join(' · '))||'—'}</span>${statuses.length?`<span class="tags status-tag">${esc(statuses.join(' · '))}</span>`:''}${!hidden&&before!==undefined&&before!==c.value?`<span class="preview-value">→ ${before}</span>`:''}</button>`;
 }).join('')}</div>`;
}
function homeHTML(){const b=E.makeBoard([8,2,6,1,4]);const saved=storage.get('mask-session-v1');return `${header()}<main class="landing"><section><div class="eyebrow">数字可以改变 · 秘密也有价格</div><h1>暗面</h1><p class="tagline">你的底牌。你的布局。<br>给你的秘密，开个价。</p><p class="intro">随机五位暗盘，三选一逐次改写。<br>对手想看你的数字？由你报价，<br>但由他决定：谁来付钱。</p><div class="start-actions"><button class="primary" data-act="tutorial">${learned()?'重新练习零基础教程':'从零学会玩 · 互动教程'}</button><button data-act="newSimple">${learned()?'入门牌桌 · 简单规则':'先进入入门牌桌'}</button><button class="subtle" data-act="newFull">完整牌桌 · 随机规则</button>${saved?'<button class="subtle" data-act="resume">继续上次的牌局</button>':''}</div></section><div class="hero-cards" aria-hidden="true"><div class="hero-card"><div class="seal"><span>暗</span></div></div><div class="hero-card main"><strong>五位蒙版</strong>${miniBoard(b)}<small>你只看见你自己的</small></div><div class="hero-card"><div class="seal"><span>？</span></div></div></div></main><footer class="landing-foot"><span>10种属性 / 10种关键词 / 10种状态<br>100种操作 × 具体位点，混合三选一</span><span>单人对战电脑 · 仅使用虚拟筹码<br>无登录，无充值。内容与平衡仍为原型。</span></footer>`;}
function draftHTML(){const p=session.players[0];return `${header()}<main class="draft-stage"><div class="flex between wrap"><span class="small">第${session.hand}局 · 双方已各下底${p.committed}枚</span><span>你的筹码 <span class="chip">${p.chips}</span></span></div><section class="draft-rule"><div class="eyebrow">先读规则，再选你的起点</div><h2>${esc(session.rule.title)}</h2><p>${esc(session.rule.description||describeRule(session.rule))}</p><button class="small subtle" style="margin-top:12px" data-act="ruleDetails">这条规则怎么算？</button></section><div class="card-row">${session.mainOffers[0].map((b,i)=>maskCardHTML(b,i)).join('')}</div><div class="draft-actions"><button data-act="reroll" ${p.chips<p.rerolls+1?'disabled':''}>重刷三张 · ${p.rerolls+1}枚</button><p>同一次选择重刷依次花1、2、3…枚。选定后不能重选。<br>费用不进奖池。对手不会看见这三张候选。</p></div></main>`;}
function playHTML(){
 const s=session,p=s.players[0],other=s.players[1],isTurn=s.active===0&&s.phase==='play',revealed=s.phase==='result'&&!s.result.isFold;
 const selectedCard=isTurn?s.offers[0][selected]:null;const targets=selectedCard?.targets||[];
 let previewBoard=null,previewText='点选一张牌，查看它会修改哪些位置。';
 if(selectedCard){try{const preview=E.preview(p.board,selectedCard,targets);previewBoard=preview.board;const deltas=preview.result.events.filter(e=>e.before!==e.after).map(e=>`${POS[e.index]} ${e.before}→${e.after}`);previewText=deltas.length?deltas.join('，'):selectedCard.description;}catch(e){previewText=e.message;}}
 if(s.lastAnimation&&s.lastAnimation.nonce!==animated)animated=s.lastAnimation.nonce;
 let ownScore='';try{const score=scoreBoard(s.rule,p.board);ownScore=s.rule.requiresOpponent?'开牌后逐位比较':(typeof score==='number'?String(score):JSON.stringify(score));}catch{}
 const gap=G.callCost(s,0),max=G.maxRaise(s,0);raise=Math.max(1,Math.min(raise,Math.max(1,max)));
 const status=s.phase==='result'?'本局结束':s.phase==='quote'?'对手正在查验，轮到你报价':s.phase==='inspectChoice'?'请选择谁付查验费':s.active===0?'轮到你：可以选牌，也可以只跟注':'对手正在思考';
 return `${header()}<main class="table-shell"><div class="turn-banner"><span class="turn-label ${s.active===1&&s.phase==='play'?'turn-thinking':''}">第${s.hand}局 · 第${s.round}/${G.MAX_ROUNDS}轮　${status}</span><span class="small">虚拟筹码 · 目标${G.TARGET_CHIPS}枚 · 候选牌允许重复</span></div><section class="table-stage ${inspectionMode?'inspecting':''}"><div class="seat"><div class="seat-head"><span class="seat-name"><span class="avatar">你</span>你的暗盘</span><span class="chip">${p.chips}</span></div>${boardHTML(p.board,{owner:0,scope:s.rule.scope,affected:targets,previewBoard})}<div class="seat-note">数字只有你能看见 · 本局主池投入${p.committed}</div></div><div class="rule-plaque"><span class="eyebrow">本局共同规则</span><h2>${esc(s.rule.title)}</h2><p>${esc(s.rule.description||describeRule(s.rule))}</p><div class="rule-divider"></div><span class="chip big">${s.pot||s.result?.pot||0}</span><span class="score-readout">${s.phase==='result'?'最终主池':'桌上奖池'} · 自己当前指标 ${esc(ownScore)}</span><button class="stage-rule-button" data-act="ruleDetails">展开逐项计算</button></div><div class="seat"><div class="seat-head"><span class="seat-name"><span class="avatar">鸦</span>乌鸦的暗盘</span><span class="chip">${other.chips}</span></div>${boardHTML(other.board,{owner:1,hidden:!revealed,known:p.known,revision:other.history.length,scope:s.rule.scope})}<div class="seat-note">${revealed?'开牌公开全部数字':'数字保密 · 材料与状态公开'} · 主池投入${other.committed}</div></div></section>
 ${inspectionMode?'<div class="notice">点击对手的一格发起查验。对手报价后，你必须选「付钱看」或「收钱让他保密」。<button class="small subtle" data-act="cancelInspect">还没选位置，取消</button></div>':''}
 <section class="hand-zone"><div><div class="hand-caption"><h3>${isTurn?'本轮三选一':'牌桌上的选择'}</h3>${isTurn?`<button class="small subtle" data-act="reroll" ${p.chips<p.rerolls+1+gap?'disabled':''}>重刷 · ${p.rerolls+1}枚</button>`:'<span class="small">等待行动完成</span>'}</div><div class="card-row">${isTurn?s.offers[0].map((c,i)=>cardHTML(c,i,{active:i===selected})).join(''):`<div class="empty-hand">${s.phase==='result'?'这一局已经结束。可以展开对账，或继续下一局。':'对手只能根据自己的盘、公开操作和付费查验决策。<br>它不知道你的秘密数字。'}</div>`}</div></div><aside class="control-dock"><h3>${selectedCard?esc(selectedCard.name):'你的决定'}</h3><div class="preview-note">${isTurn?esc(previewText):'每次操作立即生效。开牌不会重新排列过去的效果。'}</div>${isTurn?`<label class="range-row">加注 <input aria-label="加注筹码" id="raise" type="range" min="1" max="${Math.max(1,max)}" value="${raise}" ${max<1?'disabled':''}><output id="raiseOut">${raise}</output></label><button class="primary" data-act="play" ${selectedCard&&max>=1?'':'disabled'}>落牌并加注 · 共付<span id="payment">${gap+raise}</span>枚</button><p>补齐差额${gap}枚 ＋ 加注${raise}枚。牌面位置固定，不能临时换位置。</p><div class="action-row"><button data-act="call"  >${gap?'跟注 · '+Math.min(gap,p.chips)+'枚'+(p.chips<gap?'（全下）':''):'过牌 · 不改盘'}</button><button data-act="open" ${G.canOpen(s,0)?'':'disabled'}>开牌${gap?' · 补'+gap:''}</button></div><div class="action-row"><button data-act="inspect" ${p.inspected?'disabled':''}>${p.inspected?'查验已使用':'查验一格'}</button><button class="danger" data-act="fold">弃牌</button></div><div class="action-row"><button class="subtle" data-act="sidebet" ${p.turns!==0||p.bet?'disabled':''}>${p.bet?'赌注已贴出':'贴一张赌注牌'}</button></div>`:s.phase==='result'?`<button class="primary" data-act="result">查看结算</button><button data-act="nextHand">下一局</button>`:'<p>你仍然可以点自己的格子查看材料、关键词与状态，或打开牌库。</p>'}</aside></section><footer class="bottom-log"><span>桌边记录</span><div class="log-lines">${s.log.slice(-3).map(l=>`<p>${esc(l.text)}</p>`).join('')}</div><button class="small subtle" data-act="log">全部</button></footer><p class="tiny-rules">双方各行动一次后可开牌；连续两人只跟注／过牌自动开牌。数字边界 −30～30，防止无限膨胀。首版每局最多8轮。</p></main>`;
}
function wrapDialog(title,body,wide=false){return `<div class="veil" role="presentation"><section class="dialog ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="close-row"><h2>${esc(title)}</h2><button class="small subtle" data-act="close" aria-label="关闭窗口">✕</button></div>${body}</section></div>`;}
function helpHTML(){return wrapDialog('第一次来？从这里看',`<p><strong>鼠标左键／手机轻点即可，不需要拖拽。</strong>数字和筹码都是虚拟的。按“从零教程”可以在一张安全练习桌上一步一步操作。</p><div class="actions"><button class="primary" data-act="tutorial">从零教程 · 实际点一遍</button></div><h3>一局怎么进行</h3><ol><li>先读公共规则；三张随机五位主牌里选一张。对手看不到你的候选和数字。</li><li>你的回合，属性、关键词、状态、操作混合三选一。每张已写死作用位置。</li><li>点牌看高亮与预览，设加注金额，再点“落牌并加注”确认。修改立即生效，不是等待开牌再重排图层。</li><li>也可只跟注，不改盘；没人加过注时就是免费过牌。加注提高对手继续的成本。</li><li>双方各行动一次后可补齐差额开牌。连续两人只跟注／过牌也会开牌。最多8轮。</li><li>赢者拿主池；平局退回主池各自投入。弃牌让对手拿主池，但不公开底牌。</li></ol><h3>查验不是白问</h3><p>每局一次，自己的回合点击“查验一格”，再点对手格子。秘密主人报价，申请者二选一：付钱看数字；或收取同额筹码，让对方保密。对手查你时，角色反过来。报价只能是双方都付得起的整数，也可以报0。</p><h3>重刷与钱</h3><p>每次新的三选一，重刷费从1开始，之后2、3……递增。它是支付给牌桌的费用，不进奖池。查验费直接在双方之间转移。为了不产生无法跟注的边池，加注最多不超过对手剩余筹码。</p><h3>格子上的三类规则</h3><p>属性：一种材料，新属性替换旧属性。关键词：附加行为，不同种类可共存。状态：有剩余次数，在拥有者后续回合开始触发并衰减。具体触发以牌面说明为准。结束状态不撤销过去的数字变化。</p><h3>赌注牌</h3><p>自己第一次行动前可押一张，1—3枚，预测对手开牌时的状态。命中含本金返还两倍，未中归零；弃牌则取消并退款。赔付来自有限的虚拟庄家库存，与主池分开。</p><h3>已查过的数字</h3><p>金色数字表示当前确认；“上次见”表示历史观察，之后已发生无法直接确认的修改。不要把历史值当现值。公开交换可追踪已知值。格子和日志都能点开看。</p><h3>原型范围</h3><p>本版对战电脑，不是联网对战。所有130种基础牌型直接开放。电脑只使用自己的盘、公开出牌历史和合法查验，不能读取你的底牌。随机规则使用有限、可验证的结构生成；计算详情会列明每项。平衡尚在测试中。</p>`,true);}
function catalogHTML(){const list=G.allCardInstances().filter(c=>(catalogFilter==='all'||c.kind===catalogFilter)&&(!catalogSearch||(c.name+c.description).includes(catalogSearch)));return wrapDialog('牌库 · 每张都写清位置',`<div class="catalog-count">${OPERATIONS.length}种操作 / ${ATTRIBUTES.length}种属性 / ${KEYWORDS.length}种关键词 / ${STATUSES.length}种状态 · 展开位置后共${G.allCardInstances().length}张具体牌。不是把＋1、＋2重复算成不同操作类型。</div><div class="catalog-controls"><input id="catalogSearch" aria-label="搜索牌名或效果" placeholder="搜索：中央、交换、导体…" value="${esc(catalogSearch)}"><select id="catalogFilter" aria-label="筛选牌型">${[['all','全部混合'],['operation','操作'],['attribute','属性'],['keyword','关键词'],['status','状态']].map(([v,n])=>`<option value="${v}" ${catalogFilter===v?'selected':''}>${n}</option>`).join('')}</select></div><div class="catalog-count">找到${list.length}张，显示前${Math.min(catalogLimit,list.length)}张。所有牌都可在正式桌抽到。</div><div class="catalog-grid">${list.slice(0,catalogLimit).map((c,i)=>cardHTML(c,i,{action:'catalogCard'})).join('')}</div>${list.length>catalogLimit?'<div class="actions"><button data-act="moreCatalog">再显示36张</button></div>':''}`,true);}
function cellDialog(owner,index){const p=session?.players[owner];if(!p)return;const c=p.board.cells[index],visible=owner===0||(session.phase==='result'&&!session.result.isFold);const fact=session.players[0].known[index];dialog={type:'custom',title:`${owner?'对手':'你的'}${POS[index]}位`,html:`<p>数字：<strong>${visible?c.value:fact?`${fact.value}（${fact.revision===p.history.length?'当前确认':'历史观察，之后发生过修改'}）`:'保密；可在自己的回合申请查验'}</strong></p><h3>属性</h3><p>${c.attribute?esc(ATTRIBUTES.find(a=>a.id===c.attribute)?.name+'：'+ATTRIBUTES.find(a=>a.id===c.attribute)?.description):'无属性，普通材料。'}</p><h3>关键词</h3>${c.keywords.length?c.keywords.map(id=>{let d=KEYWORDS.find(k=>k.id===id);return `<p>${esc(d?.name||id)}：${esc(d?.description||'')}</p>`;}).join(''):'<p>没有关键词。</p>'}<h3>状态</h3>${Object.entries(c.statuses).length?Object.entries(c.statuses).map(([id,st])=>{let d=STATUSES.find(k=>k.id===id);return `<p>${esc(d?.name||id)} · 剩余${st.turns}次：${esc(d?.description||'')}</p>`;}).join(''):'<p>没有持续状态。</p>'}`};render();}
function ruleDetailsHTML(rule,board){let score;try{score=scoreBoard(rule,board);if(typeof score!=='string')score=JSON.stringify(score);}catch{score='尚未选主牌';}return `<p>${esc(rule.description||describeRule(rule))}</p><p>参与位置：${(rule.scope||[0,1,2,3,4]).map(i=>POS[i]).join('、')}。</p><p>当前自己指标：${esc(score)}</p><p>比较方式：${rule.mode==='min'?'越小越好':rule.mode==='target'?'越接近指定目标越好':'按牌面说明比较'}。同分不偷换规则，主池下注原数退回。</p><p class="small">规则标识：${esc(rule.id)}</p>`;}
function modalHTML(){
 if(mode==='game'&&session?.phase==='quote'){let p=session.pending;return wrapDialog('对手要看你的'+POS[p.index]+'位',`<p>由你报价，由对手决定谁付钱。它可以付你钱看数字，也可以收你的钱，让你继续保密。</p><p>双方都付得起的最高报价：${p.max}枚。报0意味着它能免费看。</p><label class="range-row">报价<input id="quoteRange" aria-label="查验报价" type="range" min="0" max="${p.max}" value="${Math.min(3,p.max)}"><output id="quoteOut">${Math.min(3,p.max)}</output></label><div class="actions"><button class="primary" data-act="submitQuote">确认报价，交给对手选择</button></div>`);}
 if(mode==='game'&&session?.phase==='inspectChoice'&&session.pending.requester===0){const p=session.pending;return wrapDialog('对手给秘密报价了',`<p>你申请查验它的${POS[p.index]}位。现在你决定谁付钱，两个选项都是真实的筹码转移。</p><div class="inspection-card"><span class="small">报价</span><br><strong>${p.price}</strong><p>不是加进奖池，而是直接交给另一方。</p></div><div class="actions"><button class="primary" data-act="inspectPay">付${p.price}枚 · 看这个数字</button><button data-act="inspectReceive">收${p.price}枚 · 让它保密</button></div>`);}
 if(!dialog)return '';
 if(dialog.type==='help')return helpHTML();if(dialog.type==='catalog')return catalogHTML();
 if(dialog.type==='result'){
 const r=session.result,win=r.winner===null?'平局':r.winner===0?'你赢下了这局':'这一局归乌鸦';
 return wrapDialog('本局结算',`<div class="settle-title"><h2>${win}</h2><p>${esc(r.reason)}</p><div class="net">本局净变化 ${r.net[0]>=0?'+':''}${r.net[0]} 枚</div></div>${!r.isFold?`<div class="result-boards"><div class="center">你的终盘${miniBoard(session.players[0].board)}</div><div class="center">对手终盘${miniBoard(session.players[1].board)}</div></div><h3>${esc(session.rule.title)}</h3><p>${esc(r.comparison.reason)}</p><div class="settle-formula">你：${esc(r.comparison.details?.[0])}<br>对手：${esc(r.comparison.details?.[1])}</div>`:'<p>弃牌不揭对手的数字，不结算赌注条件。</p>'}<table><tr><th>项目</th><th>你</th><th>对手</th></tr><tr><td>投入主池</td><td>${session.players[0].committed}</td><td>${session.players[1].committed}</td></tr><tr><td>获得主池</td><td>${r.payout[0]}</td><td>${r.payout[1]}</td></tr><tr><td>剩余筹码</td><td>${session.players[0].chips}</td><td>${session.players[1].chips}</td></tr></table>${r.bets.map(b=>`<p>${b.who?'对手':'你'}的「${esc(b.name)}」：${b.hit===null?'取消，退回本金':b.hit?'命中，含本金返还'+b.stake*2+'枚':'未中，损失'+b.stake+'枚'}。</p>`).join('')}<p class="small">净变化还包含重刷费、查验收支与独立赌注。每项可在桌边记录查看。</p><div class="actions"><button class="primary" data-act="nextHand">继续下一局</button><button data-act="log">查看完整记录</button></div>`);
 }
 if(dialog.type==='sidebet')return wrapDialog('贴在对手身上的赌注',`<p>独立的赌注三选一：可刷新，也可不选直接退出。每局第一次行动前最多押一张，不占辅牌行动。命中含本金返还两倍，未中归零；弃牌退本金。</p><div class="card-row">${session.betOffers.map((b,i)=>{return cardHTML({...b,kind:'bet'},i,{action:'chooseBet'});}).join('')}</div><label class="range-row" style="margin-top:20px">押注<input id="betStake" aria-label="赌注筹码" type="range" min="1" max="${Math.max(1,G.maxSideBet(session,0))}" value="1"><output id="betOut">1</output></label><div class="actions"><button data-act="rerollBet">换一批 · ${(session.betRerolls||0)+1}枚</button><button data-act="close">不选，返回牌桌</button></div><p class="small">点击牌即确认押注；当前最多${G.maxSideBet(session,0)}枚。没有额外押注上限；仅使用虚拟筹码。</p>`,true);
 if(dialog.type==='log')return wrapDialog('桌边记录',`<div class="log-full">${session.log.map(l=>`<p><span class="small">第${l.round}轮</span>　${esc(l.text)}</p>`).join('')}</div>`,true);
 if(dialog.type==='rule')return wrapDialog('规则逐项说明',ruleDetailsHTML(session.rule,session.players[0].board||session.mainOffers[0][0]));
 if(dialog.type==='ruleLab'){const a=E.makeBoard([8,2,6,1,4]),b=E.makeBoard([3,7,4,9,2]),r=evaluateRule(dialog.rule,a,b);return wrapDialog('随机规则实验',`<p>这不会改变当前对局。两张固定盘，在不同规则下可能有不同赢家。</p><div class="result-boards"><div class="center">甲${miniBoard(a)}</div><div class="center">乙${miniBoard(b)}</div></div><h3>${esc(dialog.rule.title)}</h3><p>${esc(dialog.rule.description)}</p><p>${esc(r.reason)}</p><div class="settle-formula">甲：${esc(r.details?.[0])}<br>乙：${esc(r.details?.[1])}</div><div class="actions"><button class="primary" data-act="anotherRule">生成另一条合法规则</button></div><p class="small">使用有类型的条件、空间范围、指标与比较方式组合，不执行任意生成的代码。平局允许退注。</p>`);}
 if(dialog.type==='foldConfirm')return wrapDialog('确定弃掉这一局？',`<p>已经投入主池的${session.players[0].committed}枚归对手，剩余${session.players[0].chips}枚保留到下一局。底牌不公开，独立赌注退回。</p><div class="actions"><button class="danger" data-act="confirmFold">确定弃牌</button><button data-act="close">继续考虑</button></div>`);
 if(dialog.type==='skip')return wrapDialog('要先学会操作吗？',`<p>本游戏不是普通的比大小。建议先完成互动教程，尤其是“你报价、对方选谁付钱”的查验规则。</p><div class="actions"><button class="primary" data-act="tutorial">先学会再玩</button><button data-act="skipConfirmed" data-simple="${dialog.simple?'1':'0'}">我已了解，直接试一局</button></div>`);
 return wrapDialog(dialog.title,dialog.html,dialog.wide);
}

function tutorialCard(kind){
 let base;
 if(kind==='plus'){base=CARD_LIBRARY.find(c=>c.operationId==='add_two')||CARD_LIBRARY.find(c=>c.kind==='operation'&&c.description.includes('增加2'));}
 else base=CARD_LIBRARY.find(c=>c.kind===kind&&(kind!=='status'||/增加|增长|生长/.test(c.description)));
 base??=CARD_LIBRARY.find(c=>c.kind===kind)||CARD_LIBRARY[0];
 return {...base,id:'lesson-'+kind,shape:'fixed',targets:[4],name:kind==='plus'?'中央＋2':base.name+' · 中'};
}
function beginLesson(){mode='tutorial';dialog=null;lesson={step:0,board:E.makeBoard([4,2,5,3,6]),other:E.makeBoard([5,3,4,2,7]),chips:30,selected:false,applied:false,seen:false,revealed:false,feedback:'',offers:[E.makeBoard([4,2,5,3,6]),E.makeBoard([9,0,1,8,2]),E.makeBoard([3,5,6,2,4])]};render();}
function advanceLesson(){lesson.step++;lesson.selected=false;lesson.feedback='';if(LESSONS[lesson.step]?.action==='status')lesson.board=E.makeBoard([4,2,5,3,6]);if(LESSONS[lesson.step]?.action==='reveal'){lesson.board=E.makeBoard([8,2,6,1,4]);lesson.other=E.makeBoard([3,7,4,9,2]);}render();}
function tutorialHTML(){const step=LESSONS[lesson.step],action=step.action;let interaction='';
 if(action==='main')interaction=`<div class="card-row">${lesson.offers.map((b,i)=>maskCardHTML(b,i,'lessonMain')).join('')}</div>`;
 else{
 let previewBoard=null;if(action==='apply')try{previewBoard=E.preview(lesson.board,tutorialCard('plus'),[4]).board;}catch{}
 interaction=`<div class="demo-rule">${lesson.step>=2?'练习规则：五处分别比大小，赢的位置多者获胜':'练习桌 · 所有筹码都是虚拟的'}</div><div class="lesson-two-boards"><div class="center"><p class="small">你的五位暗盘</p>${boardHTML(lesson.board,{lessonBoard:true,owner:0,affected:action==='apply'?[4]:[],previewBoard})}</div><div class="center"><p class="small">对手的五位暗盘</p>${boardHTML(lesson.other,{lessonBoard:true,owner:1,hidden:!lesson.revealed,known:lesson.seen?[null,null,null,null,{value:7,revision:0}]:[],revision:0,affected:action==='inspect'?[4]:[]})}</div></div>`;
 if(['select','apply'].includes(action))interaction+=`<div class="card-row">${cardHTML(tutorialCard('plus'),0,{action:'lessonSelect',active:action==='apply'})}</div>`;
 if(['attribute','keyword','status','tick'].includes(action)){const kind=action==='tick'?'status':action;interaction+=`<div class="card-row">${cardHTML(tutorialCard(kind),0,{action:'lessonRead'})}</div>`;}
 if(['reroll1','reroll2'].includes(action))interaction+=`<div class="card-row">${G.allCardInstances().slice(lesson.step*3,lesson.step*3+3).map((c,i)=>cardHTML(c,i,{action:'lessonRead'})).join('')}</div>`;
 }
 if(action==='inspectionChoice')interaction+=`<div class="inspection-card">对手报价 <strong>3</strong> 枚</div><div class="demo-controls"><button class="primary" data-act="lessonInspectPay">我付3枚，查数字</button><button data-act="lessonInspectReceive">他付3枚，继续保密</button></div>`;
 else if(action==='quote')interaction+=`<label class="range-row" style="margin-top:22px">你的报价<input id="lessonQuote" aria-label="练习查验报价" type="range" min="0" max="9" value="3"><output id="lessonQuoteOut">3</output></label><div class="demo-controls"><button class="primary" data-act="lessonQuote">确认这个价格</button></div>`;
 else if(step.button)interaction+=`<div class="demo-controls"><button class="primary pulse" data-act="lessonDo">${step.button}</button></div>`;
 return `${header()}<main class="lesson"><div class="lesson-header"><span>零基础教程 · ${lesson.step+1}/${LESSONS.length}</span><div class="lesson-progress"><span style="width:${(lesson.step+1)/LESSONS.length*100}%"></span></div><span class="chip">练习筹码 ${lesson.chips}</span></div><div class="lesson-body"><section class="lesson-copy"><span class="eyebrow">手把手练习 / 无需卡牌经验</span><h2>${step.title}</h2><p>${step.text}</p><p class="task">${step.task}</p><p class="small">不需要背全部牌。正式桌里，点格子看效果，点“怎么玩”随时复习。</p></section><section class="lesson-sandbox">${interaction}<p class="lesson-feedback" role="status">${esc(lesson.feedback)}</p></section></div></main>`;
}
function lessonDo(){const action=LESSONS[lesson.step].action;
 if(action==='apply'){E.executeCard(lesson.board,tutorialCard('plus'),[4]);tone(500);}
 if(['attribute','keyword','status'].includes(action))E.executeCard(lesson.board,tutorialCard(action),[4]);
 if(action==='tick'){E.tick(lesson.board);toast('回合触发完成。已发生的数字变化不会在状态到期时撤销。');}
 if(action==='reroll1')lesson.chips-=1;if(action==='reroll2')lesson.chips-=2;if(action==='call')lesson.chips-=2;
 if(action==='reveal'){lesson.revealed=true;const wins=lesson.board.cells.filter((c,i)=>c.value>lesson.other.cells[i].value).length;toast(`你赢下${wins}处；对手赢下${5-wins}处。这组终盘你获胜。`);}
 if(action==='finish'){storage.set('mask-tutorial-v1','done');startNew(true);return;}
 advanceLesson();
}
function startNew(simple){session=G.newSession(Date.now()>>>0,{simple});mode='game';dialog=null;selected=-1;inspectionMode=false;render();}
function render(){clearTimeout(aiTimer);let html=mode==='home'?homeHTML():mode==='tutorial'?tutorialHTML():session?.phase==='draft'?draftHTML():session?.phase==='matchOver'?`${header()}<main class="draft-stage center"><h1>本场牌局结束</h1><p style="margin:25px">你剩${session.players[0].chips}枚，乌鸦剩${session.players[1].chips}枚。一方筹码归零，或达到${G.TARGET_CHIPS}枚目标。</p><button class="primary" data-act="newFull">重新开一桌</button></main>`:playHTML();$('#app').innerHTML=html+modalHTML();bindInputs();if(mode==='game'){persist();scheduleAI();}}
function scheduleAI(){if(dialog&&['help','catalog'].includes(dialog.type))return;if(session?.phase==='play'&&session.active===1)aiTimer=setTimeout(()=>{try{G.runAITurn(session);selected=-1;raise=1;if(session.phase==='result')dialog={type:'result'};render();}catch(e){console.error(e);toast('对手行动未完成：'+e.message);}},700);else if(session?.phase==='inspectChoice'&&session.pending.requester===1)aiTimer=setTimeout(()=>{G.answerAIInspection(session);render();},700);}
function bindInputs(){
 $('#raise')?.addEventListener('input',e=>{raise=Number(e.target.value);$('#raiseOut').textContent=raise;$('#payment').textContent=G.callCost(session,0)+raise;});
 for(const [input,output]of [['quoteRange','quoteOut'],['betStake','betOut'],['lessonQuote','lessonQuoteOut']])$('#'+input)?.addEventListener('input',e=>$('#'+output).textContent=e.target.value);
 $('#catalogFilter')?.addEventListener('change',e=>{catalogFilter=e.target.value;catalogLimit=36;render();});
 $('#catalogSearch')?.addEventListener('input',e=>{catalogSearch=e.target.value;catalogLimit=36;const pos=e.target.selectionStart;render();$('#catalogSearch')?.focus();$('#catalogSearch')?.setSelectionRange(pos,pos);});
}
$('#app').addEventListener('click',event=>{const btn=event.target.closest('[data-act]');if(!btn||btn.disabled)return;const act=btn.dataset.act,index=Number(btn.dataset.index),pos=Number(btn.dataset.pos),owner=Number(btn.dataset.owner);try{
 if(act==='home'){mode='home';dialog=null;inspectionMode=false;render();return;}
 if(act==='sound'){sound=!sound;tone();render();return;}
 if(act==='help'){dialog={type:'help'};render();return;}
 if(act==='catalog'){dialog={type:'catalog'};catalogLimit=36;render();return;}
 if(act==='moreCatalog'){catalogLimit+=36;render();return;}
 if(act==='catalogCard'||act==='lessonRead'){toast('牌面已展示完整效果与固定位置。');return;}
 if(act==='ruleLab'||act==='anotherRule'){dialog={type:'ruleLab',rule:generateRule(Math.random)};render();return;}
 if(act==='tutorial'){beginLesson();return;}
 if(act==='newSimple'||act==='newFull'){if(!learned()){dialog={type:'skip',simple:act==='newSimple'};render();}else startNew(act==='newSimple');return;}
 if(act==='skipConfirmed'){startNew(btn.dataset.simple==='1');return;}
 if(act==='resume'){const saved=JSON.parse(storage.get('mask-session-v1')||'null');if(saved?.version!==1)throw new Error('没有可继续的有效牌局');session=saved;mode='game';dialog=null;render();return;}
 if(act==='close'){dialog=null;render();return;}
 if(act==='lessonDo'){lessonDo();return;}
 if(act==='lessonMain'){lesson.board=E.cloneBoard(lesson.offers[index]);advanceLesson();return;}
 if(act==='lessonSelect'){if(LESSONS[lesson.step].action==='select')advanceLesson();else toast('已选中。请按确认落牌。');return;}
 if(act==='lessonCell'){let action=LESSONS[lesson.step].action;if(action==='cell'&&owner===0&&pos===4){advanceLesson();return;}if(action==='inspect'&&owner===1&&pos===4){advanceLesson();return;}toast(owner?'对手数字保密。':'这是你的'+POS[pos]+'位，数字'+lesson.board.cells[pos].value);return;}
 if(act==='lessonInspectPay'||act==='lessonInspectReceive'){lesson.chips+=act==='lessonInspectPay'?-3:3;lesson.seen=act==='lessonInspectPay';toast(act==='lessonInspectPay'?'你支付3枚，查到中央是7。':'你收到3枚，中央继续保密。');advanceLesson();return;}
 if(act==='lessonQuote'){let amount=Number($('#lessonQuote').value);const buys=amount<=2;lesson.chips+=buys?amount:-amount;toast(buys?`电脑付你${amount}枚，看了你的中央。`:`电脑收取你${amount}枚，让你保密。`);advanceLesson();return;}
 if(act==='chooseMain'){G.chooseMain(session,index);selected=-1;tone(500);render();return;}
 if(act==='reroll'){G.reroll(session,0);selected=-1;tone(260);render();return;}
 if(act==='select'){selected=index;tone(420);render();return;}
 if(act==='play'){const card=session.offers[0][selected];G.playCard(session,0,selected,G.legalPlacements(card)[0],raise);selected=-1;raise=1;tone(650);if(session.phase==='result')dialog={type:'result'};render();return;}
 if(act==='call'){G.call(session,0);selected=-1;raise=1;if(session.phase==='result')dialog={type:'result'};render();return;}
 if(act==='open'){G.open(session,0);dialog={type:'result'};tone(700);render();return;}
 if(act==='fold'){dialog={type:'foldConfirm'};render();return;}
 if(act==='confirmFold'){G.fold(session,0);dialog={type:'result'};render();return;}
 if(act==='nextHand'){G.startHand(session);dialog=null;selected=-1;raise=1;render();return;}
 if(act==='inspect'){inspectionMode=true;selected=-1;render();return;}
 if(act==='cancelInspect'){inspectionMode=false;render();return;}
 if(act==='cell'){if(inspectionMode&&owner===1){G.requestInspection(session,0,pos);inspectionMode=false;render();}else cellDialog(owner,pos);return;}
 if(act==='inspectPay'||act==='inspectReceive'){G.resolveInspection(session,act==='inspectPay'?'pay':'receive');tone(550);render();return;}
 if(act==='submitQuote'){G.quoteInspection(session,Number($('#quoteRange').value));render();return;}
 if(act==='sidebet'){dialog={type:'sidebet'};render();return;}
 if(act==='rerollBet'){G.rerollSideBets(session,0);render();return;}
 if(act==='chooseBet'){G.placeSideBet(session,0,session.betOffers[index].id,Number($('#betStake').value));dialog=null;render();return;}
 if(act==='log'){dialog={type:'log'};render();return;}
 if(act==='result'){dialog={type:'result'};render();return;}
 if(act==='ruleDetails'){dialog={type:'rule'};render();return;}
 }catch(error){console.error(error);toast(error.message||String(error));}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog){dialog=null;render();}});
window.addEventListener('error',e=>{toast('遇到错误：'+e.message);});
render();
// Read-only diagnostics for local automated tests; no network/multiplayer authority is implied.
if(location.hostname==='127.0.0.1'||location.hostname==='localhost')window.maskDiagnostics={get state(){return session;},get lesson(){return lesson;},get mode(){return mode;},counts:()=>({operations:OPERATIONS.length,attributes:ATTRIBUTES.length,keywords:KEYWORDS.length,statuses:STATUSES.length,cards:G.allCardInstances().length})};
