// Public catalog: operation IDs are also the finite engine instruction set.
export const SHAPES = {
  single: [[0, 0]], pair: [[0, 0], [0, -1]],
  line: [[0, -1], [0, 0], [0, 1]],
  corners: [[0, -1], [1, 0]],
  cross: [[0, -1], [1, 0], [0, 1], [-1, 0], [0, 0]], fixed: null,
};
const entries = rows => rows.map(([id, name, description]) => ({id, name, description}));
export const ATTRIBUTES = entries([
  ['guard','止降','主变动与附带变动都不能使本格降低。'],
  ['growth','增量加一','正增量额外增加1。'],
  ['fragile','减量加一','负增量额外减少1。'],
  ['inverter','增减反转','本格收到的增量取相反数。'],
  ['small','九点边界','发生数值写入时，结果额外限制在-9至9。'],
  ['even','向零取偶','发生数值写入时，结果向零取最近偶数。'],
  ['echo','半量追加','主变动完成后，额外追加实际增量的一半（向零取整）。附带变动不再触发。'],
  ['conductor','顺位传导','主变动后，顺位下一格增加实际增量的符号。顺位为上→右→下→左→中→上。'],
  ['rooted','拒绝附带','拒绝其他格或自身触发的附带数值写入；仍接受操作与回合数值写入。'],
  ['limited','属性阶段限幅','属性处理时将增量限制在-3至3；随后关键词仍可修改增量。'],
]);
export const KEYWORDS = entries([
  ['sprout','每回合加一','每次回合结算，本格增加1。'],
  ['wither','每回合减一','每次回合结算，本格减少1。'],
  ['rebound','零值回初','主变动后若本格为0，附带写入本格开局值。'],
  ['double-rise','正增量翻倍','属性处理后，正增量乘2。'],
  ['half-fall','负增量减半','属性处理后，负增量除以2，向零取整。'],
  ['ring-pulse','外圈同号','主变动后，其他外圈格各增加实际增量的符号。'],
  ['center-pulse','中格同号','外圈格主变动后，中格增加实际增量的符号。'],
  ['trail','顺位写旧值','主变动后，顺位下一格附带写入本格本次变动前数值。'],
  ['status-proof','拒收状态','不能新安装状态；已有状态不移除。'],
  ['nonnegative','不低于零','发生数值写入时，结果最低为0。'],
]);
export const STATUSES = entries([
  ['frozen','冻结','持续2回合：拒绝所有数值写入。'],
  ['shield','一次止降','持续2回合：阻止下一次负增量后立即消耗。'],
  ['reversed','临时反转','持续2回合：属性与关键词处理前，增量取反。'],
  ['boosted','增量倍乘','持续2回合：增量乘2。'],
  ['weakened','增量折半','持续2回合：增量除以2并向零取整。'],
  ['burning','每回合减二','持续2回合：每次回合结算减少2。'],
  ['healing','每回合加二','持续2回合：每次回合结算增加2。'],
  ['charge','到期加五','持续2回合：最后一次回合结算增加5。'],
  ['doom','到期归零','持续2回合：最后一次回合结算写入0。'],
  ['muted','关键词停用','持续2回合：关键词的数值与触发效果暂停；拒收状态仍生效。'],
]).map(e => ({...e, turns: 2}));

// Each row is one distinct transformation, not a parameter-only card variant.
const unary = [
  ['add_two','加二','目标增加2。'],
  ['negate','取相反数','目标变为其相反数。'],
  ['absolute','取绝对值','目标变为其绝对值。'],
  ['square','平方','目标变为其平方。'],
  ['signed-root','带符号平方根','绝对值开平方向下取整，再还原原符号。'],
  ['halve','折半','目标除以2，向零取整。'],
  ['reciprocal','三十除本值','目标非零时写入30除以本值的向零整数；零写入0。'],
  ['mod-three','三余数','目标写入除以3的非负余数。'],
  ['decimal-digit','取个位','目标写入绝对值的个位数字。'],
  ['sign','取符号','正数写1、负数写-1、零写0。'],
  ['zero','归零','目标写入0。'],
  ['complement-nine','九减本值','目标写入9减本值。'],
  ['round-five','就近五倍数','目标写入最近的5的倍数；正中间向正方向取。'],
  ['even-up','向上取偶','目标写入不小于本值的最近偶数。'],
  ['digit-sum','数位和','目标写入绝对值的十进制数位和。'],
  ['reverse-digits','数位倒转','将绝对值十进制数位倒转，再还原符号。'],
  ['triangle-ten','十点折返','先取除以20的非负余数，再写入该数到0或20的较小距离。'],
  ['factorial-digit','个位阶乘','取绝对值个位数字的阶乘；0的阶乘为1。'],
  ['fibonacci-digit','个位斐数','取绝对值个位数字为序号的斐波那契数；序号0与1分别为0与1。'],
  ['next-prime','下一质数','写入严格大于本值的最小质数。'],
  ['bit-reverse','五位倒序','绝对值的低五位二进制倒序，结果非负。'],
  ['bit-count','一位数量','写入绝对值二进制中1的数量。'],
  ['gray-code','格雷转换','绝对值与其右移一位结果作按位异或。'],
  ['collatz','奇偶递推','偶数除以2；奇数乘3再加1。'],
  ['power-floor','二次幂下界','写入不超过绝对值的最大2的整数次幂；零写0。'],
  ['log-two','二进制位阶','写入绝对值以2为底对数的向下整数；零写0。'],
  ['divisor-count','约数数量','写入绝对值的正约数数量；零写0。'],
  ['totient','互质数量','写入1到绝对值之间与其互质的整数数量；零写0。'],
  ['proper-divisor-sum','真约数和','写入绝对值的小于自身的正约数之和；零写0。'],
  ['digital-root','数字根','反复取绝对值的数位和直到剩一位。'],
  ['triangular','三角数','取绝对值n，写入n乘(n+1)再除以2。'],
  ['bit-complement','五位取反','写入绝对值低五位逐位取反的数。'],
  ['restore-initial','回到开局','写入目标自己的开局数值。'],
  ['restore-previous','回到前值','写入目标最近一次实际变动前的数值。'],
  ['repeat-delta','重复上次增量','目标加上自己最近一次实际变动的增量。'],
  ['delta-magnitude','上次变化幅度','目标写入自己最近一次实际变动的增量的绝对值。'],
  ['initial-gap','开局距离','写入本值与自己的开局值的绝对差。'],
  ['initial-midpoint','开局中点','写入本值与自己的开局值的平均数，向零取整。'],
  ['initial-gcd','开局公约数','写入本值绝对值与自己开局值绝对值的最大公约数；双零写0。'],
  ['initial-xor','开局异或','写入本值绝对值与自己开局值绝对值的按位异或。'],
];
const aggregate = [
  ['board-sum','全盘总和','目标写入全盘五格之和。'],
  ['board-mean','全盘均值','目标写入全盘均值，向零取整。'],
  ['board-median','全盘中位','目标写入全盘排序后的第三个数。'],
  ['board-min','全盘最小','目标写入全盘最小值。'],
  ['board-max','全盘最大','目标写入全盘最大值。'],
  ['board-range','全盘极差','目标写入全盘最大值减最小值。'],
  ['board-mode','全盘众数','目标写入出现最多的值；并列取较小值。'],
  ['distinct-count','不同值数量','目标写入全盘不同数值数量。'],
  ['positive-count','正数数量','目标写入全盘严格正数的数量。'],
  ['sign-balance','正负数量差','目标写入全盘正数数量减负数数量。'],
  ['absolute-sum','绝对值总和','目标写入全盘绝对值之和。'],
  ['root-mean-square','均方根','目标写入全盘平方均值的平方根，向下取整。'],
  ['mean-deviation','偏离均值','目标写入本值减全盘均值，向零取整。'],
  ['dense-rank','不同值名次','目标写入本值在全盘不同数值升序中的名次，从1起。'],
  ['nearest-gap','最近数值距离','目标写入自己与其他四格数值的最小绝对差。'],
  ['center-distance','距中格数值','目标写入本值与中格数值的绝对差。'],
  ['board-gcd','全盘公约数','目标写入全盘绝对值的最大公约数；全零写0。'],
  ['board-product','全盘乘积','目标写入全盘五格的乘积。'],
  ['missing-nonnegative','最小缺失数','目标写入全盘未出现的最小非负整数。'],
  ['frequency','本值频数','目标写入本值在全盘出现的次数。'],
  ['other-sum','其余总和','目标写入其余四格之和。'],
  ['greater-sum','较大值之和','目标写入全盘严格大于本值的格子之和。'],
  ['median-distance','离中位距离','目标写入本值与全盘中位数的绝对差。'],
  ['pair-distance-sum','到各格距离和','目标写入本值到其余四格数值的绝对差总和。'],
  ['board-variance','全盘方差','目标写入全盘总体方差，向下取整。'],
];
const fixed = [
  ['rotate-ring','外圈顺时针','旧左→上，旧上→右，旧右→下，旧下→左；中不变。'],
  ['swap-center-max','中格交换最大','中格与全盘最大格交换；并列按上右下左中优先。'],
  ['sort-cross','顺位升序','五个旧值从小到大依次写入上、右、下、左、中。'],
  ['reverse-rank','值序镜像','每个旧值换成全盘排序中镜像名次的值；重复值取首次名次。'],
  ['center-copy','中值铺外圈','旧中格值写入上右下左，中不变。'],
  ['ring-mean-center','外圈均值入中','旧上右下左均值向零取整写入中。'],
  ['swap_ud','上下交换','只交换上格和下格的数值；其他格不变。'],
  ['opposite-sum','对面相加','上加旧下、下加旧上、右加旧左、左加旧右；中不变。'],
  ['opposite-difference','对面相减','上减旧下、下减旧上、右减旧左、左减旧右；中不变。'],
  ['neighbor-sum','外圈邻值和','每个外圈格写入其顺时针与逆时针相邻外圈旧值之和；中不变。'],
  ['ring-gradient','外圈前后差','每个外圈格写入顺时针下一格旧值减逆时针上一格旧值；中不变。'],
  ['laplacian','外圈二阶差','外圈各写入两侧外圈旧值之和减自身旧值的2倍；中不变。'],
  ['axis-gradient','两轴差入中','中写入旧上减旧下加旧右减旧左。'],
  ['swap_rc','中右交换','只交换中格和右格的数值；其他格不变。'],
  ['radial-add','中值加外圈','上右下左分别加旧中值；中不变。'],
  ['balance-extremes','极值各靠近一','最小格加1、最大格减1；并列按上右下左中优先；两格相同时不变。'],
  ['equalize-total','总和均分','总和先向下除以5，各格写入商；余数从上右下左中依次各补1。'],
  ['prefix-sum','顺位前缀和','按上右下左中，各格写入从上至本格的旧值之和。'],
  ['suffix-max','顺位后缀最大','按上右下左中，各格写入本格到中格的旧值最大值。'],
  ['running-mean','顺位前缀均值','按上右下左中，各格写入从上至本格的旧值均值，向零取整。'],
  ['first-difference','顺位相邻差','上不变；右、下、左、中分别写入自身旧值减顺位前一格旧值。'],
  ['opposite-product','对面相乘','每个外圈格乘对面旧值；中不变。'],
  ['opposite-gcd','对面公约数','每个外圈格写入自身与对面旧值绝对值的最大公约数；中不变。'],
  ['opposite-lcm','对面公倍数','每个外圈格写入自身与对面旧值绝对值的最小公倍数；任一零则为0；中不变。'],
  ['soft-threshold','按中值收缩','外圈绝对值减去旧中格绝对值，最低为0，再还原各自符号；中不变。'],
  ['winsorize','极值收进一位','所有值限制在旧排序第二小与第二大值之间。'],
  ['normalize-range','极差映射','把旧最小值映射为0、最大值为10，其他线性映射向下取整；全相同写0。'],
  ['center-reservoir','外圈移一点入中','每个非零外圈向零移动1；中格加上外圈旧值的符号之和。'],
  ['positive-pool','正值汇入中','外圈正值归零，中格增加这些正值总和；外圈非正值不变。'],
  ['bubble-pass','顺位冒泡一遍','按上右下左中，从前向后比较相邻两值，前大于后则交换，恰好四次比较。'],
  ['alternating-sum','交错和入中','中写入旧上减旧右加旧下减旧左加旧中。'],
  ['orthogonal-projection','纵横均值','上、下写入两者旧均值；右、左写入两者旧均值；均向零取整，中不变。'],
  ['median-filter','外圈三值中位','每个外圈格写入自身及两侧外圈旧值的中位数；中不变。'],
  ['difference-of-products','两轴乘积差','中写入旧上乘旧下减旧右乘旧左。'],
  ['center-split','中值分给外圈','旧中值向零除以4所得商加给各外圈，中写入余数。'],
];
export const OPERATIONS = [
  ...unary.map(([id,name,description]) => ({id,name,description,category:'unary', instruction:id})),
  ...aggregate.map(([id,name,description]) => ({id,name,description,category:'aggregate', instruction:id})),
  ...fixed.map(([id,name,description]) => ({id,name,description,category:'fixed', instruction:id,
    fixedTargets:id==='swap_ud' ? [0,2] : id==='swap_rc' ? [1,4] :
      ['ring-mean-center','axis-gradient','alternating-sum','difference-of-products'].includes(id) ? [4] :
      ['rotate-ring','center-copy','opposite-sum','opposite-difference','neighbor-sum','ring-gradient','laplacian','radial-add','opposite-product','opposite-gcd','opposite-lcm','soft-threshold','median-filter'].includes(id) ? [0,1,2,3] : [0,1,2,3,4],
    ...(id==='swap_ud' ? {permutation:{0:2,2:0}} : id==='swap_rc' ? {permutation:{1:4,4:1}} :
      id==='rotate-ring' ? {permutation:{0:3,1:0,2:1,3:2}} : {})})),
];
const masks = ['single','pair','line','corners','cross'];
export const CARD_LIBRARY = [
  ...OPERATIONS.map((op,i) => ({id:`op-${op.id}`,name:op.name,description:op.description,
    kind:'operation',operationId:op.id,shape:op.fixedTargets ? 'fixed' : masks[i % masks.length],
    cost:op.fixedTargets ? 3 : 1 + Math.floor((i % masks.length)/2),
    ...(op.fixedTargets ? {targets:[...op.fixedTargets]} : {})})),
  ...[['attribute',ATTRIBUTES],['keyword',KEYWORDS],['status',STATUSES]].flatMap(([kind, list]) =>
    list.map((effect,i) => ({id:`${kind}-${effect.id}`,name:effect.name,description:effect.description,
      kind,effectId:effect.id,shape:masks[i % masks.length],cost:2}))),
];
