import type { KeywordSpec } from "./keywords.js";
export const CHARACTER_KEYWORDS: Record<string, KeywordSpec[]> = {
  WR1: [{ kind: "rage", value: 2 }],
  WR2: [{ kind: "rage", value: 3 }],
  EN1: [{ kind: "intercept", value: 3 }],
  LU1: [
    { kind: "guard", value: 1 },
    { kind: "ward", value: 1 },
  ],
  SL3: [{ kind: "ward", value: 1 }],
  GL3: [{ kind: "legacy", value: 4 }],
  LU4: [{ kind: "echo", value: 2 }],
  GL5: [{ kind: "pursuit", value: 3 }],
  GR2: [
    { kind: "reserve", value: 3 },
    { kind: "inspire", value: 2 },
  ],
  EN4: [
    { kind: "intercept", value: 2 },
    { kind: "pursuit", value: 1 },
  ],
  GR1: [{ kind: "inspire", value: 3 }],
  GR3: [{ kind: "link", value: 2 }],
  PR3: [{ kind: "command", value: 3 }],
  SL4: [{ kind: "inspire", value: 2 }],
  WR4: [{ kind: "pursuit", value: 2 }],
  LU5: [{ kind: "echo", value: 1 }],
};
export const CHARACTER_SUMMARIES: Record<string, string> = {
  WR1: "激怒 2。对手每次主动下注或加注，另 +1，最多 +3。",
  WR2: "激怒 3。原数落后对位至少 2 时，另 +2。",
  WR3: "对手下过注或加过注，获得原数一半的力量。",
  GR1: "激励 3。每投入 10 筹码，另 +1，最多 +4。",
  GR2: "蓄能 3 · 激励 2。每次付装备费，另 +1，最多 +3。",
  GR3: "结盟 2。己方每个装备位另提供 +1。",
  GL1: "原数小于对位：自己 +2，对位 −2。",
  GL2: "吞噬左邻：沉默其人物，获得它原数一半的力量。",
  GL3: "遗赠 4。自己是队内最低原数且对位不超过 7 时，另 +2。",
  EN1: "截流 3。与对位原数相差不超过 1 时，另 +1。",
  EN2: "补齐与对位的原数差距；原数不落后则不补。",
  EN3: "封印对位装备；对位有装备时，自己另 +1。",
  SL1: "每次过牌蓄力 +1，最多 +3。",
  SL2: "低数（3～4）时，把自己的原数再加一遍。",
  SL3: "护盾。没付过装备费，己方全体 +1。",
  PR1: "高数（8～10）时，力量 +2。",
  PR2: "原数领先对位至少 3：获得原数一半的力量。",
  PR3: "统御 3。自己是队内最高的高数（可并列）：另外两位各 +2。",
  LU1: "护送 · 护盾。自己 −2，左右邻位各 +2。",
  LU2: "缔结静默：同时沉默自己与对位人物。",
  LU3: "原数低于对位时，压低对位 3 点。",
  WR4: "追猎 2。对位装了装备，另 +3。",
  GR4: "剩余筹码比对手多时，自己 +3。",
  GL4: "对位装了装备，压低对位 2 点。",
  GL5: "追猎 3。对位是敌方最低原数时，另 +1。",
  EN4: "截流 2 · 追猎 1。对位是高数时，另 +1。",
  SL4: "激励 2。撑到第 4 轮，另 +3。",
  LU4: "共鸣 2。原数落后对位时，对位 −2、右邻 +1。",
  LU5: "共鸣 1。站在中间，己方全体另 +1。",
};
export const EQUIPMENT_KEYWORDS: Record<
  string,
  {
    name: string;
    kind: KeywordSpec["kind"];
    values: [number, number, number];
    base: [number, number, number];
    icon: string;
    extra?: { kind: KeywordSpec["kind"]; values: [number, number, number] };
  }
> = {
  E03: {
    name: "万象齿轮",
    kind: "inspire",
    values: [2, 2, 1],
    base: [2, 1, 1],
    icon: "♧",
  },
  E05: {
    name: "盟约斗篷",
    kind: "link",
    values: [2, 1, 1],
    base: [2, 2, 1],
    icon: "⋈",
  },
  E09: {
    name: "誓约盾",
    kind: "ward",
    values: [1, 1, 1],
    base: [3, 2, 1],
    icon: "◈",
  },
  E10: {
    name: "护送链甲",
    kind: "guard",
    values: [1, 1, 1],
    base: [3, 2, 1],
    icon: "♜",
  },
  E11: {
    name: "遗赠护符",
    kind: "legacy",
    values: [3, 2, 1],
    base: [2, 1, 1],
    icon: "✧",
  },
  E12: {
    name: "截流镜",
    kind: "intercept",
    values: [3, 2, 1],
    base: [1, 1, 1],
    icon: "⇄",
  },
  E14: {
    name: "共鸣链",
    kind: "echo",
    values: [3, 2, 1],
    base: [1, 1, 1],
    icon: "⌁",
  },
  E15: {
    name: "统御旌旗",
    kind: "command",
    values: [3, 2, 1],
    base: [2, 1, 1],
    icon: "♛",
  },
  E18: {
    name: "蓄能器",
    kind: "reserve",
    values: [4, 3, 2],
    base: [1, 1, 1],
    icon: "⚡",
  },
  E19: {
    name: "百相旗",
    kind: "inspire",
    values: [3, 2, 1],
    base: [1, 1, 1],
    icon: "♧",
  },
  E21: {
    name: "诱饵甲",
    kind: "rage",
    values: [4, 3, 2],
    base: [1, 1, 1],
    icon: "✹",
  },
  E22: {
    name: "传能滑轮",
    kind: "echo",
    values: [2, 1, 1],
    base: [1, 1, 1],
    icon: "⌁",
    extra: { kind: "reserve", values: [2, 2, 1] },
  },
  E24: {
    name: "猎王印",
    kind: "pursuit",
    values: [3, 2, 1],
    base: [1, 1, 1],
    icon: "➶",
  },
};
export const EQUIPMENT_SUMMARIES: Record<string, (v: number) => string> = {
  E01: (v) => `稳定力量 +${v}。`,
  E02: (v) => `低数（3～4）时 +${v}。`,
  E03: (v) => `中数（5～7）时 +${v}。`,
  E04: (v) => `对位是低数时 +${v}。`,
  E05: (v) => `左邻力量 +${v}。`,
  E06: (v) => `对位是敌方最低原数时 +${v}。`,
  E07: (v) => `对位是高数时 +${v}。`,
  E08: (v) => `自己是高数时 +${v}。`,
  E11: (v) => `自己是己方最低原数时 +${v}。`,
  E13: (v) => `原数落后对位至少 3 时 +${v}。`,
  E15: (v) => `站中间且是高数：另外两位各 +${v}。`,
  E16: (v) => `自己是己方最低原数时，另 +${v}。`,
  E17: (v) => `自己是己方最高原数时，另 +${v}。`,
  E19: (v) => `己方原数之和至少 21 时，另 +${v}。`,
  E20: (v) => `自己被沉默时，另 +${v}；装备仍然有效。`,
  E22: (v) => `自己原数不高于另外两位的平均值时，另 +${v}。`,
  E23: (v) => `自己原数介于另外两位之间时，另 +${v}，不限位置或间隔。`,
};
