import { Rng } from "../rng.js";
import { NUMERIC_CHARACTER_IDS, NUMERIC_ARENAS, NUMERIC_RULES, NUMERIC_EFFECTS, NUMERIC_EQUIPMENT, runNumericResolution, type NumericSlot, type NumericTeam } from "./content.js";
import type { NumericAction, NumericObservation } from "./types.js";
type S=0|1; const flip=(s:S):S=>s===0?1:0;
type P={numbers:number[];current:string[];seen:string[];kept:string[];rerolled:boolean;slots:NumericSlot[]|null;equipment:({id:string;tier:string}|null)[];stack:number};
export class NumericTable {
 readonly rng:Rng; readonly players:[P,P]; phase="draft"; handNo=1; dealer:S=0; pot=0; arenaId:string;ruleId:string;
 effects:{id:string;status:string}[]; private actors:S[]=[0,1];private round=1;private contributions:[number,number]=[0,0];private target=0;private acted:[boolean,boolean]=[false,false]; private opDone:[boolean,boolean]=[false,false]; private ops:[number,number]=[0,0]; private checks:[number,number]=[0,0]; private raises:[number,number]=[0,0];
 private votes:[boolean|null,boolean|null]=[null,null];private bids:[number|null,number|null]=[null,null];private offers:string[]=[];
 private outcome:NumericObservation["result"]=null;
 constructor(opts:{seed?:number;buyIn?:number}={}){this.rng=new Rng(opts.seed??Date.now());const buy=opts.buyIn??100;
 const mk=():P=>({numbers:[],current:[],seen:[],kept:[],rerolled:false,slots:null,equipment:[null,null,null],stack:buy});
 this.players=[mk(),mk()];
 this.arenaId=this.rng.pick(NUMERIC_ARENAS).id;this.ruleId=this.rng.pick(NUMERIC_RULES).id;this.effects=this.rng.sample(NUMERIC_EFFECTS,3).map(x=>({id:x.id,status:"pending"}));
 for(const s of [0,1] as S[]){this.players[s].numbers=[this.rng.int(8)+3,this.rng.int(8)+3,this.rng.int(8)+3];this.draw(s,9);this.pay(s,2);}
 }
 private draw(s:S,n:number){const p=this.players[s],pool=NUMERIC_CHARACTER_IDS.filter(x=>!p.seen.includes(x));p.current=this.rng.sample(pool,Math.min(n,pool.length));p.seen.push(...p.current);}
 private pay(s:S,n:number){const x=Math.min(this.players[s].stack,n);this.players[s].stack-=x;this.pot+=x;return x;}
 observe(s:S):NumericObservation{const p=this.players[s],f=this.players[flip(s)];return {phase:this.phase,handNo:this.handNo,round:this.round,dealer:this.dealer,stacks:[this.players[0].stack,this.players[1].stack],pot:this.pot,toAct:[...this.actors],arenaId:this.arenaId,ruleId:this.ruleId,effects:this.effects.map(x=>({...x})),opFee:Math.min(2,p.stack),bidCap:Math.min(p.stack,20),me:{numbers:[...p.numbers],current:[...p.current],kept:[...p.kept],rerolled:p.rerolled,slots:p.slots?.map(x=>({...x}))??null,equipment:p.equipment.map(x=>x&&{...x}),offers:this.phase==="equip"?[...this.offers]:null},opponent:{tiers:[...f.numbers].sort((a,b)=>b-a).map(x=>x<=4?"低":x>=8?"高":"中"),placed:!!f.slots,equipment:f.equipment.map(x=>x&&{...x})},betting:{toCall:Math.max(0,this.target-this.contributions[s]),minRaiseTo:this.target+2,target:this.target,roundBet:[...this.contributions]},result:this.outcome};}
 apply(s:S,a:NumericAction){if(!this.actors.includes(s))throw Error("未轮到该玩家");const p=this.players[s];
 if(this.phase==="draft"){if(a.type==="keep"){const id=p.current[a.index];if(!id||p.kept.includes(id))throw Error("不能锁定");p.kept.push(id);p.current.splice(a.index,1);if(p.kept.length===3){this.actors=this.actors.filter(x=>x!==s);if(!this.actors.length){this.phase="place";this.actors=[0,1];}}return;}if(a.type==="reroll"&&!p.rerolled){p.rerolled=true;this.draw(s,9);return;}throw Error("只能选牌或 D 一次");}
 if(this.phase==="place"){if(a.type!=="place")throw Error("先排位");if(new Set(a.effects).size!==3||new Set(a.numbers).size!==3||a.effects.some(x=>x<0||x>2)||a.numbers.some(x=>x<0||x>2))throw Error("数字、效果需各用一次");p.slots=a.numbers.map((n,i)=>({number:p.numbers[n],effectId:p.kept[a.effects[i]],equipment:null}));this.actors=this.actors.filter(x=>x!==s);if(!this.actors.length)this.betStart();return;}
 if(this.phase==="bet"){if(a.type==="fold"){this.finish(flip(s));return;}const call=Math.max(0,this.target-this.contributions[s]);if(a.type==="check"&&call===0||a.type==="call"&&call>0){if(a.type==="call")this.contributions[s]+=this.pay(s,call);else this.checks[s]++;this.acted[s]=true;this.betNext(s);return;}let to:number;if(a.type==="allIn")to=this.contributions[s]+p.stack;else if(a.type==="raise")to=a.to;else if(a.type==="bet")to=this.contributions[s]+a.amount;else throw Error("下注动作无效");if(!Number.isInteger(to)||to<=this.target||to-this.contributions[s]>p.stack)throw Error("下注额度无效");this.contributions[s]+=this.pay(s,to-this.contributions[s]);this.raises[s]++;this.target=to;this.acted[s]=true;this.acted[flip(s)]=false;this.actors=[flip(s)];return;}
 if(this.phase==="operate"){if(a.type!=="operate")throw Error("请选择操作");this.opDone[s]=true;this.actors=this.actors.filter(x=>x!==s);if(a.draft&&this.round<=7){this.phase="equip";this.actors=[s];const ids=[...new Set(NUMERIC_EQUIPMENT.map(x=>x.id))];this.offers=this.rng.sample(ids,3);return;}this.operated();return;}
 if(this.phase==="equip"){
  if(a.type==="operate"&&!a.draft){this.opDone[s]=true;this.phase="operate";this.offers=[];this.actors=this.opDone[flip(s)]?[]:[flip(s)];this.operated();return;}
  if(a.type!=="equip")throw Error("请选择装备或跳过");const id=this.offers[a.offerIndex],sl=p.slots?.[a.pos];if(!id||!sl)throw Error("装备无效");if(this.round<=3&&sl.equipment)throw Error("普通装备不能覆盖");const tier=this.tier();sl.equipment={id,tier};p.equipment[a.pos]={id,tier};this.ops[s]++;this.phase="operate";this.offers=[];this.actors=this.opDone[flip(s)]?[ ]:[flip(s)];this.operated();return;}
 if(this.phase==="vote"){if(a.type!=="vote")throw Error("请表决");this.votes[s]=a.activate;this.actors=this.actors.filter(x=>x!==s);if(!this.actors.length){if(this.votes[0]===this.votes[1]){this.effects[this.round-1].status=this.votes[0]?"active":"inactive";this.nextRound();}else{this.phase="bid";this.actors=[0,1];}}return;}
 if(this.phase==="bid"){if(a.type!=="bid"||a.amount<0||a.amount>Math.min(20,p.stack))throw Error("暗标无效");this.bids[s]=a.amount;this.actors=this.actors.filter(x=>x!==s);if(!this.actors.length){this.pay(0,this.bids[0]!);this.pay(1,this.bids[1]!);const w=this.bids[0]===this.bids[1]?this.dealer:this.bids[0]!>this.bids[1]!?0:1;this.effects[this.round-1].status=this.votes[w]?"active":"inactive";this.nextRound();}return;}
 if(this.phase==="result"&&a.type==="nextHand"){this.phase="over";this.actors=[];return;}throw Error("阶段动作无效");
 }
 private betStart(){this.phase="bet";this.actors=[flip(this.dealer)];this.acted=[false,false];this.contributions=[0,0];this.target=0;this.opDone=[false,false];}
 private betNext(s:S){const f=flip(s);if(this.acted[f]){if(this.players.some(x=>x.stack===0)){this.effects.forEach(x=>{if(x.status==="pending")x.status="inactive";});this.resolve();}else if(this.round>7){this.resolve();}else{this.phase="operate";this.actors=[0,1];}}else this.actors=[f];}
 private tier():"normal"|"replace-1"|"replace-2"{return this.round<=3?"normal":this.round<=5?"replace-1":"replace-2";}
 private operated(){if(this.actors.length)return;if(!this.opDone[0]||!this.opDone[1]){this.phase="operate";this.actors=[this.opDone[0]?1:0];return;}if(this.round<=3){this.phase="vote";this.votes=[null,null];this.bids=[null,null];this.actors=[0,1];}else this.nextRound();}
 private nextRound(){this.round++;this.betStart();}
 private finish(w:S){this.phase="result";this.actors=[0];this.outcome={winner:w,trace:[`玩家 ${w} 因对手弃牌获胜`]};}
 private resolve(){const teams=this.players.map(p=>({slots:p.slots!})) as [NumericTeam,NumericTeam];const stats=[0,1].map(s=>({invested:this.contributions[s],betOrRaise:this.raises[s],checks:this.checks[s],opsPaid:this.ops[s],stack:this.players[s].stack,round:this.round})) as [{invested:number;betOrRaise:number;checks:number;opsPaid:number;stack:number;round:number},{invested:number;betOrRaise:number;checks:number;opsPaid:number;stack:number;round:number}];const r=runNumericResolution({teams,arenaId:this.arenaId,ruleId:this.ruleId,activeEffectIds:this.effects.filter(x=>x.status==="active").map(x=>x.id),stats});this.phase="result";this.actors=[0];this.outcome={winner:r.winner,teams:teams.map(t=>t.slots.map(x=>({effectId:x!.effectId,number:x!.number,equipmentId:x!.equipment?.id??null}))),powers:r.powers,lineWinners:r.lineWinners,trace:r.trace,lines:r.lines};}
 aiAction(s:1):NumericAction|null{const o=this.observe(s);if(!o.toAct.includes(s))return null;if(o.phase==="draft")return{type:"keep",index:0};if(o.phase==="place")return{type:"place",numbers:[0,1,2],effects:[0,1,2]};if(o.phase==="bet")return o.betting.toCall?{type:"call"}:{type:"check"};if(o.phase==="operate")return{type:"operate",draft:this.round<=7&&this.players[s].equipment.some(x=>!x)};if(o.phase==="equip")return{type:"equip",offerIndex:0,pos:Math.max(0,this.players[s].equipment.findIndex(x=>!x))};if(o.phase==="vote")return{type:"vote",activate:this.rng.next()>.5};if(o.phase==="bid")return{type:"bid",amount:Math.min(2,this.players[s].stack)};return null;}
}
