// Data-only content. Stable IDs are also the future illustration/animation keys.
export const KEYWORDS = {
  charge: "冲锋：首次接敌时快速突进并追加伤害；站定时不发动。",
  double: "连击：每次攻击分为两次伤害，分别消耗圣盾。",
  shield: "圣盾：抵挡一次伤害；每场开战恢复初始圣盾。",
  taunt: "嘲讽：附近敌人选目标时优先攻击此单位。",
  pierce: "贯穿：射线继续伤害目标后方的敌人。",
  push: "击退：命中后将敌人推远，可打断架设。",
  guard: "护卫：身旁队友受到的部分伤害转由自己承受。",
  siege: "架设：站稳1.2秒后伤害提高；位移会重置。",
  pull: "牵引：每次攻击将目标拉近。",
  heal: "疗愈：优先治疗射程内受伤最重的队友，无人受伤时攻击。",
  splash: "溅射：伤害目标附近的其它敌人。",
  drain: "汲取：造成伤害后恢复部分生命。",
  armor: "护甲：每次生命伤害减去护甲，最低为1。",
  slow: "寒缚：命中降低目标移动速度2秒。",
  execute: "处决：对低于三成生命的目标伤害提高。",
  thorns: "反伤：受击后返还少量伤害，不反复触发。",
  ward: "结界：周期性为附近一名队友补充圣盾。",
  haste: "疾速：更短的攻击间隔。",
  reach: "长兵：可隔着前排攻击稍远的敌人。",
  regen: "再生：作战中缓慢回复生命。",
};
const unitRows = [
  [
    "铁誓卫士",
    "knight",
    2,
    108,
    12,
    58,
    1.25,
    29,
    ["taunt", "armor"],
    "盾墙不是装饰。",
  ],
  [
    "无首骑士",
    "rider",
    2,
    82,
    21,
    58,
    1.35,
    47,
    ["charge"],
    "失去头颅，仍记得敌人的方向。",
  ],
  [
    "双刃侍从",
    "blade",
    1,
    56,
    9,
    54,
    0.95,
    40,
    ["double"],
    "第一刀问路，第二刀作答。",
  ],
  [
    "圣烛修女",
    "priest",
    2,
    72,
    8,
    175,
    1.6,
    29,
    ["heal", "shield"],
    "灯还亮着，就不许死。",
  ],
  [
    "缚日巨像",
    "colossus",
    3,
    170,
    28,
    83,
    2.3,
    20,
    ["splash", "armor"],
    "背负一颗不肯熄灭的太阳。",
  ],
  [
    "穿星弓手",
    "archer",
    2,
    65,
    17,
    245,
    1.65,
    30,
    ["pierce"],
    "星辰只是箭途中的孔洞。",
  ],
  [
    "负钟者",
    "bell",
    3,
    145,
    23,
    145,
    2.1,
    23,
    ["push", "splash"],
    "钟响之后，阵线退后三步。",
  ],
  [
    "逆棘守卫",
    "knight",
    2,
    119,
    10,
    60,
    1.4,
    26,
    ["thorns", "guard"],
    "每道伤口都要偿还。",
  ],
  [
    "灰羽斥候",
    "archer",
    1,
    46,
    9,
    185,
    0.8,
    48,
    ["haste"],
    "追不上箭，就追不上它的影子。",
  ],
  ["虚空钩手", "hook", 2, 84, 11, 240, 2.1, 26, ["pull"], "远处并不是安全。"],
  [
    "葬礼炮手",
    "cannon",
    3,
    94,
    34,
    275,
    2.55,
    19,
    ["siege", "splash"],
    "等一秒，为你掘一座墓。",
  ],
  [
    "镜盾步兵",
    "knight",
    1,
    67,
    8,
    54,
    1.25,
    29,
    ["shield"],
    "一次豁免，也是一条命。",
  ],
  [
    "血契剑客",
    "blade",
    2,
    84,
    18,
    57,
    1.15,
    36,
    ["drain"],
    "伤口向另一具身体索取利息。",
  ],
  [
    "断罪猎手",
    "archer",
    2,
    70,
    16,
    205,
    1.4,
    34,
    ["execute"],
    "不追强者，只追将死之人。",
  ],
  [
    "霜墓使者",
    "mage",
    2,
    75,
    13,
    210,
    1.55,
    28,
    ["slow", "pierce"],
    "寒冷从不需要许可。",
  ],
  [
    "长枪侍卫",
    "lancer",
    1,
    62,
    12,
    104,
    1.3,
    32,
    ["reach"],
    "多出的半步，足够救命。",
  ],
  [
    "誓约执旗者",
    "banner",
    2,
    98,
    9,
    66,
    1.4,
    28,
    ["ward", "guard"],
    "旗帜落下之前，盾不会碎尽。",
  ],
  [
    "荒野屠夫",
    "blade",
    2,
    105,
    22,
    58,
    1.6,
    33,
    ["execute", "regen"],
    "空腹而来，满身伤痕而归。",
  ],
  [
    "雷鸣双子",
    "mage",
    2,
    64,
    10,
    215,
    1.3,
    31,
    ["double", "slow"],
    "你听见的回声，也会杀人。",
  ],
  [
    "亡国禁卫",
    "knight",
    3,
    162,
    14,
    70,
    1.3,
    24,
    ["taunt", "guard", "armor"],
    "王国已经没有人值得保护。",
  ],
  [
    "锁链巡礼者",
    "hook",
    1,
    58,
    8,
    148,
    1.7,
    33,
    ["pull"],
    "邀请从来不必温柔。",
  ],
  [
    "烬火投手",
    "mage",
    1,
    48,
    11,
    176,
    1.8,
    33,
    ["splash"],
    "手中的余烬，还记得大火。",
  ],
  [
    "银月游骑",
    "rider",
    2,
    76,
    15,
    172,
    1.25,
    48,
    ["charge", "pierce"],
    "月光先抵达战场。",
  ],
  [
    "裂城攻槌",
    "colossus",
    3,
    152,
    29,
    78,
    2,
    22,
    ["charge", "push"],
    "城门只是另一种肋骨。",
  ],
  [
    "黑帷医师",
    "priest",
    1,
    49,
    5,
    155,
    1.55,
    30,
    ["heal"],
    "缝好伤口，再谈价钱。",
  ],
  [
    "不眠石像",
    "colossus",
    2,
    120,
    13,
    66,
    1.5,
    21,
    ["regen", "thorns"],
    "它一直在等你先动手。",
  ],
  [
    "王庭决斗者",
    "blade",
    2,
    79,
    15,
    63,
    1.15,
    39,
    ["double", "shield"],
    "公平只是胜者的修辞。",
  ],
  [
    "黄昏弩车",
    "cannon",
    2,
    81,
    25,
    280,
    2.2,
    18,
    ["siege", "pierce"],
    "瞄准的是队列，不是个人。",
  ],
  [
    "逐日信使",
    "lancer",
    1,
    52,
    10,
    62,
    1.05,
    57,
    ["charge"],
    "尚未抵达，就已倾尽所有。",
  ],
  [
    "夜幕织者",
    "mage",
    2,
    73,
    12,
    225,
    1.65,
    29,
    ["ward", "slow"],
    "织一块敌人走不出的夜。",
  ],
];
export const UNITS = unitRows.map((r, i) => ({
  id: `u${i + 1}`,
  name: r[0],
  art: r[1],
  pop: r[2],
  hp: r[3],
  atk: r[4],
  range: r[5],
  interval: r[6],
  speed: r[7],
  tags: r[8],
  flavor: r[9],
}));
export const UNIT_BY_ID = Object.fromEntries(UNITS.map((x) => [x.id, x]));
export const EFFECTS = {
  fury: { name: "烈刃", text: "攻击提高30%，持续2场", atk: 0.3, duration: 2 },
  bulwark: { name: "重铠", text: "护甲+5，持续2场", armor: 5, duration: 2 },
  sun: {
    name: "太阳之矢",
    text: "获得贯穿，攻击+10%，持续2场",
    tag: "pierce",
    atk: 0.1,
    duration: 2,
  },
  moon: {
    name: "月之庇护",
    text: "下2场开战额外获得1层圣盾",
    shields: 1,
    duration: 2,
  },
  tempest: {
    name: "疾风",
    text: "攻击间隔缩短25%，持续2场",
    rate: 0.25,
    duration: 2,
  },
  wings: {
    name: "疾行",
    text: "速度+40%，射程+25，持续2场",
    speed: 0.4,
    range: 25,
    duration: 2,
  },
  thunder: {
    name: "雷鸣复调",
    text: "获得连击，持续1场",
    tag: "double",
    duration: 1,
  },
  hook: {
    name: "锁链",
    text: "获得牵引，射程+35，持续2场",
    tag: "pull",
    range: 35,
    duration: 2,
  },
  bell: { name: "震荡", text: "获得击退，持续2场", tag: "push", duration: 2 },
  thorn: {
    name: "逆棘",
    text: "获得反伤，护甲+2，持续2场",
    tag: "thorns",
    armor: 2,
    duration: 2,
  },
  guard: {
    name: "守望",
    text: "获得护卫，护甲+3，持续2场",
    tag: "guard",
    armor: 3,
    duration: 2,
  },
  crown: {
    name: "挑战王冠",
    text: "获得嘲讽，护甲+5，持续2场",
    tag: "taunt",
    armor: 5,
    duration: 2,
  },
  cannon: {
    name: "攻城姿态",
    text: "获得架设，射程+45，持续2场",
    tag: "siege",
    range: 45,
    duration: 2,
  },
  frost: {
    name: "霜缚",
    text: "获得寒缚，射程+20，持续2场",
    tag: "slow",
    range: 20,
    duration: 2,
  },
  feast: {
    name: "血宴",
    text: "获得汲取，攻击+10%，持续2场",
    tag: "drain",
    atk: 0.1,
    duration: 2,
  },
  ember: {
    name: "余烬",
    text: "获得溅射，持续2场",
    tag: "splash",
    duration: 2,
  },
  judge: {
    name: "斩刑",
    text: "获得处决，攻击+15%，持续2场",
    tag: "execute",
    atk: 0.15,
    duration: 2,
  },
  lance: { name: "长夜之枪", text: "射程+85，持续2场", range: 85, duration: 2 },
  charge: {
    name: "突袭",
    text: "获得冲锋，速度+20%，持续2场",
    tag: "charge",
    speed: 0.2,
    duration: 2,
  },
  ward: { name: "护幕", text: "获得结界，持续2场", tag: "ward", duration: 2 },
  regen: { name: "不息", text: "获得再生，持续2场", tag: "regen", duration: 2 },
  mend: { name: "缝合", text: "立即恢复指定存活单位30生命", heal: 30 },
  mendAll: {
    name: "休战片刻",
    text: "所有存活单位立即恢复12生命",
    heal: 12,
    all: true,
  },
  steelAll: {
    name: "集体武装",
    text: "所有存活单位护甲+2，持续1场",
    armor: 2,
    all: true,
    duration: 1,
  },
  wrathAll: {
    name: "全军奋起",
    text: "所有存活单位攻击+12%，持续1场",
    atk: 0.12,
    all: true,
    duration: 1,
  },
  shelter: {
    name: "临终豁免",
    text: "指定存活单位恢复15生命，并在下场额外获得1层圣盾",
    heal: 15,
    shields: 1,
    duration: 1,
  },
};
const cardRows = [
  ["第二颗太阳", "sun", "moon"],
  ["不许退场", "cannon", "charge"],
  ["王冠的重量", "crown", "wings"],
  ["血债血偿", "feast", "mend"],
  ["万剑归鞘", "fury", "bulwark"],
  ["落雷敕令", "thunder", "frost"],
  ["葬钟为谁鸣", "bell", "regen"],
  ["铁幕之后", "guard", "lance"],
  ["最后一根火柴", "ember", "mendAll"],
  ["星辰坠落之夜", "sun", "ward"],
  ["众生俯首", "hook", "crown"],
  ["拒绝安息", "regen", "shelter"],
  ["空王座", "fury", "guard"],
  ["无声的裁决", "judge", "frost"],
  ["风暴眼", "tempest", "moon"],
  ["深渊邀约", "hook", "feast"],
  ["镜中军团", "moon", "thunder"],
  ["世界尽头的枪", "lance", "charge"],
  ["叛旗升起", "wrathAll", "steelAll"],
  ["神不会流血", "bulwark", "feast"],
  ["归还伤口", "thorn", "mend"],
  ["你仍欠我一命", "shelter", "judge"],
  ["天火降诏", "ember", "sun"],
  ["冰封的誓言", "frost", "bulwark"],
  ["无名者的凯歌", "steelAll", "wrathAll"],
  ["背水之誓", "charge", "mendAll"],
  ["不灭的微光", "ward", "regen"],
  ["黑日初升", "moon", "feast"],
  ["审判尚未结束", "judge", "shelter"],
  ["兵临永夜", "lance", "ward"],
  ["为王开路", "bell", "charge"],
  ["命运的倒钩", "hook", "thorn"],
  ["誓言快于刀刃", "tempest", "guard"],
  ["双生灾星", "thunder", "ember"],
  ["群山回应", "cannon", "bell"],
  ["葬下胜利", "mendAll", "fury"],
  ["孤城不降", "bulwark", "cannon"],
  ["穿过你的黎明", "sun", "wings"],
  ["温柔的铁律", "guard", "frost"],
  ["长眠之前", "mend", "regen"],
  ["迟来的赦免", "shelter", "mendAll"],
  ["断剑仍是剑", "fury", "thorn"],
  ["无人接过旗帜", "ward", "wrathAll"],
  ["以退为进", "wings", "bell"],
  ["刺穿祷告", "lance", "sun"],
  ["黑帷落下", "frost", "hook"],
  ["第十三次心跳", "regen", "tempest"],
  ["王的倒影", "crown", "moon"],
  ["所有人都要活着", "mendAll", "steelAll"],
  ["我们拒绝结局", "thunder", "shelter"],
];
export const CARDS = cardRows.map((r, i) => ({
  id: `c${i + 1}`,
  name: r[0],
  success: r[1],
  failure: r[2],
  art: `card-${i + 1}`,
}));
// Rules compare a shared observable on both sides. Equality satisfies both.
const metrics = [
  ["markHp", "王的伤口", "标记单位剩余生命百分比", "ratio", "任一主阵单位"],
  ["centerPop", "阵线", "中央交战区存活总人口", "pop", "人口"],
  ["shield", "余辉", "存活单位的剩余圣盾层数", "shield", "圣盾 / 结界"],
  ["alivePop", "余军", "本场上阵单位的存活总人口", "pop", "人口"],
  ["health", "残躯", "上阵单位剩余生命总和", "hp", "生命"],
  ["damage", "交锋", "本场造成的实际生命伤害", "damage", "攻击"],
  ["kills", "葬礼", "本场击杀的敌方单位数", "kill", "击杀"],
  ["killPop", "斩将", "击杀的敌方总人口", "kill", "人口"],
  ["advance", "长征", "存活单位中最远的推进距离", "move", "移动"],
  ["rear", "守家", "己方后排内的己方存活人数", "position", "站定 / 移动"],
  ["breach", "越境", "存活且位于敌方后排的己方人数", "position", "冲锋 / 牵引"],
  ["hits", "剑雨", "实际命中敌人的攻击段数", "hit", "连击 / 溅射"],
  ["shieldBreak", "碎光", "打破敌方圣盾的总层数", "shield", "圣盾 / 多段"],
  [
    "healing",
    "缝补",
    "本场有效治疗量（不计溢出）",
    "heal",
    "疗愈 / 汲取 / 再生",
  ],
  ["push", "逐客", "对敌人造成的总击退距离", "push", "击退"],
  ["pull", "赴宴", "对敌人造成的总牵引距离", "pull", "牵引"],
  ["multi", "回响", "一次攻击命中多名敌人的次数", "multi", "贯穿 / 溅射"],
  [
    "centerTime",
    "驻守",
    "己方所有单位在交战区内的累计秒数",
    "move",
    "移动 / 站定",
  ],
  ["guarded", "代价", "护卫替队友承受的伤害量", "guard", "护卫"],
  ["rangeAlive", "余箭", "存活远程单位人数（射程至少150）", "ranged", "远程"],
  ["meleeAlive", "余刃", "存活近战单位人数（射程小于150）", "melee", "近战"],
  ["untouched", "洁净", "本场未损失过生命且仍存活的人数", "hp", "护盾 / 保护"],
  ["markDamage", "王之剑", "标记单位造成的实际生命伤害", "damage", "标记单位"],
  ["armorBlock", "铁衣", "护甲累计减免的伤害量", "armor", "护甲"],
  ["wounded", "伤兵", "存活且生命低于自身上限一半的人数", "hp", "伤害 / 疗愈"],
];
export const RULES = metrics.flatMap((r, i) =>
  [1, -1].map((direction, j) => ({
    id: `r${i * 2 + j + 1}`,
    name: `${r[1]} · ${j ? "逆誓" : "立誓"}`,
    metric: r[0],
    direction,
    description: `${r[2]}${j ? "不高于" : "不低于"}对方即成功。相等时双方成功。`,
    label: r[2],
    icon: r[3],
    counter: r[4],
  })),
);
// Pledges are public, one-use, and evaluated on the frozen battle snapshot.
const pledges = [
  ["寸土必争", "centerPop", 2, "bulwark"],
  ["阵线不倒", "centerPop", 4, "steelAll"],
  ["不失一卒", "losses", 0, "mendAll", "max"],
  ["有去有回", "alivePop", 4, "mend"],
  ["五人同行", "aliveCount", 4, "wrathAll"],
  ["向王宣战", "markDamage", 35, "judge"],
  ["君王亲征", "markDamage", 70, "fury"],
  ["王座尚存", "markHp", 50, "moon"],
  ["毫发无损", "markHp", 90, "ward"],
  ["君王染血", "markHp", 30, "feast", "max"],
  ["第一滴血", "kills", 1, "charge"],
  ["双重葬礼", "kills", 2, "thunder"],
  ["猎杀巨人", "killPop", 3, "lance"],
  ["终结军势", "killPop", 5, "ember"],
  ["拒绝溃散", "alivePop", 6, "guard"],
  ["越过中线", "advance", 190, "wings"],
  ["长驱直入", "advance", 340, "charge"],
  ["后方来客", "breach", 1, "hook"],
  ["后排坚守", "rear", 2, "cannon"],
  ["最后一面盾", "shield", 1, "moon"],
  ["圣光不灭", "shield", 3, "ward"],
  ["碎裂祷告", "shieldBreak", 1, "tempest"],
  ["击碎神话", "shieldBreak", 3, "sun"],
  ["刀锋不歇", "hits", 12, "fury"],
  ["百刃序曲", "hits", 25, "thunder"],
  ["以血为证", "damage", 80, "feast"],
  ["赤色战场", "damage", 150, "ember"],
  ["紧急缝合", "healing", 15, "mend"],
  ["生者之责", "healing", 35, "regen"],
  ["退后三步", "push", 40, "bell"],
  ["逐出王庭", "push", 100, "crown"],
  ["请君入瓮", "pull", 35, "hook"],
  ["深渊归客", "pull", 90, "frost"],
  ["一次穿透", "multi", 1, "sun"],
  ["连锁噩梦", "multi", 3, "lance"],
  ["坚守十秒", "centerTime", 10, "bulwark"],
  ["漫长驻防", "centerTime", 30, "guard"],
  ["替你受伤", "guarded", 12, "shelter"],
  ["背负众人", "guarded", 30, "thorn"],
  ["弓弦未断", "rangeAlive", 2, "cannon"],
  ["刀刃尚温", "meleeAlive", 2, "charge"],
  ["仍有净土", "untouched", 1, "moon"],
  ["平安归队", "untouched", 2, "mendAll"],
  ["铁甲之誓", "armorBlock", 12, "steelAll"],
  ["不破之躯", "armorBlock", 30, "bulwark"],
  ["带伤归来", "wounded", 1, "mend"],
  ["缝合队列", "wounded", 2, "mendAll"],
  ["绝不后退", "rear", 0, "wrathAll", "max"],
  ["寂静刀锋", "hits", 8, "frost", "max"],
  ["克制杀意", "kills", 0, "ward", "max"],
];
const pledgeLabels = {
  ...Object.fromEntries(metrics.map((r) => [r[0], r[2]])),
  aliveCount: "本场上阵单位的存活人数",
  losses: "本场己方阵亡人数",
};
export const PLEDGES = pledges.map((r, i) => ({
  id: `p${i + 1}`,
  name: r[0],
  metric: r[1],
  threshold: r[2],
  reward: r[3],
  direction: r[4] === "max" ? -1 : 1,
  description: `${pledgeLabels[r[1]]}${r[4] === "max" ? "不超过" : "至少"}${r[2]}。兑现：${EFFECTS[r[3]].text}。`,
}));
export const CONTENT = {
  units: UNITS,
  cards: CARDS,
  rules: RULES,
  pledges: PLEDGES,
};
export const findContent = (id) =>
  Object.values(CONTENT)
    .flat()
    .find((x) => x.id === id);
