import fs from 'node:fs';
import path from 'node:path';
const root=import.meta.dirname;
const files=['00-战斗约定.md','01-人物.md','02-装备与槽位.md','03-胜利规则.md','04-场地与公共效果.md','05-构筑与审核.md'];
const expected={WR:14,GR:14,GL:14,EN:14,SL:14,LU:14,PR:14,EQ:50,FX:50,VC:30,AR:20,PE:50};
const docs=files.map(file=>({file,text:fs.readFileSync(path.join(root,file),'utf8')}));
const entries=[];
for(const doc of docs){const headings=[...doc.text.matchAll(/^### ((?:WR|GR|GL|EN|SL|LU|PR|EQ|FX|VC|AR|PE)\d{2})[｜|]([^\n]*)/gm)];for(let i=0;i<headings.length;i++){const m=headings[i],tailStart=m.index+m[0].length,boundary=doc.text.slice(tailStart).search(/\r?\n#{1,3} /),end=boundary<0?doc.text.length:tailStart+boundary;entries.push({id:m[1],name:m[2].trim(),category:m[1].slice(0,2),source:doc.file,text:doc.text.slice(m.index,end).trim()});}}
const counts=Object.fromEntries(Object.keys(expected).map(k=>[k,entries.filter(e=>e.category===k).length]));
const problems=[];for(const [k,v]of Object.entries(expected))if(counts[k]!==v)problems.push(`${k}: ${counts[k]} != ${v}`);
const ids=new Set();for(const e of entries){if(ids.has(e.id))problems.push(`重复编号 ${e.id}`);ids.add(e.id);}
for(const doc of docs)for(const match of doc.text.matchAll(/\b(?:WR|GR|GL|EN|SL|LU|PR|EQ|FX|VC|AR|PE)\d{2}\b/g))if(!ids.has(match[0]))problems.push(`不存在的引用 ${match[0]} in ${doc.file}`);
if(problems.length)throw Error(problems.join('\n'));
fs.writeFileSync(path.join(root,'catalog.json'),JSON.stringify({version:1,status:'design-not-implemented',counts,entries},null,2));
fs.writeFileSync(path.join(root,'完整设计稿.md'),docs.map(d=>d.text).join('\n\n---\n\n'));
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');
const sections=docs.map((d,i)=>`<section id="doc${i}" data-section="${i}"><div class="doc-label">${esc(d.file)}</div>${d.text.split(/\r?\n/).filter(Boolean).map(l=>{const h=l.match(/^(#{1,3}) (.+)/);if(h){const id=h[2].match(/^([A-Z]{2}\d{2})/);return `<h${h[1].length}${id?` id="${id[1]}"`:''}>${inline(h[2])}</h${h[1].length}>`;}return `<p>${inline(l)}</p>`;}).join('')}</section>`).join('');
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>七罪暗队 · 完整内容设计</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#171a19;color:#e9e5db;font:16px/1.9 system-ui,'Microsoft YaHei',sans-serif}header{padding:44px max(24px,calc((100vw - 1020px)/2));background:#222824;border-bottom:1px solid #525e4c}header h1{margin:0;font-size:32px;color:#e7c997}header p{max-width:840px;color:#c4cabc}nav{position:sticky;top:0;background:#202622f5;display:flex;flex-wrap:wrap;gap:10px;padding:12px 24px;border-bottom:1px solid #455143;z-index:1}a,button{color:#e7c997}nav button{border:1px solid #5b6755;background:none;border-radius:20px;padding:7px 14px;cursor:pointer;font:inherit;font-size:14px}nav button.active{background:#e7c997;color:#202622}main{max-width:1050px;margin:auto;padding:24px}section{padding-bottom:80px}h1,h2,h3{line-height:1.5;scroll-margin-top:120px}section h1{font-size:27px}h2{margin-top:44px;color:#e7c997;border-bottom:1px solid #485344;padding-bottom:12px}h3{margin:30px 0 10px;padding:12px 16px;border-left:3px solid #c6a266;background:#252e27;font-size:19px}p{margin:9px 0;color:#d4d8cd}strong{color:#f0e1c5}.doc-label{font-size:12px;color:#91a28b}.badge{display:inline-block;border:1px solid #58664f;padding:4px 12px;margin:6px 8px 0 0;border-radius:6px}input{max-width:400px;width:100%;background:#171e19;color:white;border:1px solid #718366;padding:12px;border-radius:6px;font:inherit}.search-result{padding:20px;margin:12px 0;background:#252e27;border-radius:8px}.search-result a{font-weight:700}[hidden]{display:none!important}@media(max-width:600px){body{font-size:15px}header{padding:26px 20px}main{padding:16px}nav{padding:8px;gap:6px}nav button{padding:5px 9px;font-size:12px}h3{font-size:17px}}
</style><header><h1>七罪暗队</h1><p>人物、装备、槽位效果与公共战场的完整设计首稿。所有数值是待验证起点，不是已完成平衡的游戏。</p><div>${['98 人物','50 装备','50 槽位效果','30 胜利规则','20 场地','50 公共效果'].map(s=>`<span class="badge">${s}</span>`).join('')}</div></header><nav>${['战斗约定','98个人物','装备与效果','胜利规则','场地与环境','构筑与审核'].map((s,i)=>`<button data-tab="${i}">${s}</button>`).join('')}<button data-tab="all">全文</button><button data-tab="search">搜索</button></nav><main><section id="search" hidden><h2>按名字、编号或机制找牌</h2><input id="query" placeholder="例如：护盾、WR01、连击"><div id="results"></div></section>${sections}</main><script>
const entries=${JSON.stringify(entries).replaceAll('<','\\u003c')};const buttons=[...document.querySelectorAll('[data-tab]')];
function show(tab){document.querySelectorAll('[data-section]').forEach(s=>s.hidden=tab!=='all'&&s.dataset.section!==tab);document.querySelector('#search').hidden=tab!=='search';buttons.forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
buttons.forEach(b=>b.onclick=()=>{show(b.dataset.tab);window.scrollTo({top:0})});
const escape=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));document.querySelector('#query').oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelector('#results').innerHTML=q?entries.filter(c=>(c.id+' '+c.text).toLowerCase().includes(q)).slice(0,80).map(c=>'<div class="search-result"><a href="#'+c.id+'" data-id="'+c.id+'">'+escape(c.id+' '+c.name)+'</a><p>'+escape(c.text.split('\\n').slice(1).join(' '))+'</p></div>').join(''):'';};document.querySelector('#results').onclick=e=>{const a=e.target.closest('[data-id]');if(a){show('all');setTimeout(()=>document.getElementById(a.dataset.id).scrollIntoView(),0)}};show('0');
</script></html>`;
fs.writeFileSync(path.join(root,'review.html'),html);
console.log(JSON.stringify({counts,total:entries.length,duplicateIds:0,brokenReferences:0,outputs:['review.html','完整设计稿.md','catalog.json']},null,2));
