import {CARDS,PROFESSIONS,RULES,judge} from './cards.js?v=0fac9c07a0f1';
import {LESSONS} from './tutorial.js?v=0fac9c07a0f1';
const accents={WR:'#b9544c',GR:'#ab8b42',GL:'#738356',EN:'#7d72a1',SL:'#688ea0',LU:'#a46b87',PR:'#c0a16c',N:'#788a90',U:'#b4a475'};
const symbols={WR:'怒',GR:'贪',GL:'食',EN:'妒',SL:'怠',LU:'欲',PR:'傲'};
let oldPending='',oldLife=null;
export function renderTable(ui,h){
 const {state:s,selection:sel,mode,lesson,complete,busy,handKind,cardMode}=ui;
 const {esc,btn,options,choiceUI}=h;
 if(!s)return '';
 const p=s.players[0],o=s.players[1],pending=s.pending,l=mode==='tutorial'?LESSONS[lesson]:null;
 const changed=pending?.card.uid!==oldPending;oldPending=pending?.card.uid||'';
 const hurt=s.players.map((p,i)=>oldLife&&p.life<oldLife[i]);oldLife=s.players.map(p=>p.life);
 const interactive=!s.ended&&!s.choice&&s.turn===0&&!complete&&!busy&&!l?.info;
 const selected=uid=>p.hand.find(e=>e.uid===uid);
 const activeFields=['WR-R2','WR-R3','GR-R3','GL-R1','GL-R4','EN-R1','EN-R5','SL-R2','SL-R3','LU-R4'];
 const ruleName=id=>RULES.find(r=>r.id===id)?.name||id;
 const cost=c=>c.cost?.discard?`费用：额外弃${c.cost.discard}张手牌`:c.cost?.alienExile?'费用：放逐1张原属对手的手牌':'';
 function physicalCard(e,{action=null,picked=false,face=null,number=null,commit=false,tag=''}={}){
  const c=CARDS[e.cardId],kind={main:'主牌',support:'辅牌',field:'公共条款'}[c.kind];
  return `<${action?'button':'article'} class="playing-card ${action?'hand-card':''} ${picked?'picked':''} ${commit?'card-arrives':''} ${c.kind}" style="--card-accent:${accents[c.profession]}" ${action?`data-action="${action}" data-id="${esc(e.uid)}" aria-pressed="${picked}"`:''}>
   <div class="card-topline"><span>${esc(PROFESSIONS[c.profession]||'中立')} · ${kind}</span><span class="card-seal">${symbols[c.profession]||'◇'}</span></div><strong>${esc(c.name)}</strong>
   ${c.kind==='main'?`<div class="card-face face-success ${face==='success'?'face-lit':''}"><b>成功</b><span>${esc(c.success)}</span></div><div class="card-face face-failure ${face==='failure'?'face-lit':''}"><b>失败</b><span>${esc(c.failure)}</span></div>`:`<div class="card-full-effect"><span class="effect-mark">${c.kind==='support'?'＋':'§'}</span><p>${esc(c.text)}</p></div>`}
   <div class="card-bottom">${esc(cost(c)|| (c.kind==='main'?'下一张牌决定生效的一面':c.kind==='support'?'搭配主牌使用':'双方有效 · 持续生效'))}</div>
   ${number?`<span class="number-token">${number}</span>`:''}${picked||tag?`<span class="picked-label">${esc(tag||'已选中')}</span>`:''}
  </${action?'button':'article'}>`;
 }
 function hero(player,i){return `<div class="hero ${hurt[i]?'hero-hurt':''}" style="--hero-accent:${accents[player.profession]}"><div class="hero-medallion">${symbols[player.profession]}</div><div class="hero-info"><b>${i===0?'你':'电脑'} <span>${PROFESSIONS[player.profession]}</span></b><div class="hero-health"><i style="width:${player.life/60*100}%"></i><span>生命 ${player.life}</span></div><small>护甲 ${player.armor} <span>手牌 ${player.hand.length} · 牌库 ${player.deck.length}</span></small></div><div class="status-pips">${Object.entries(player.statuses).map(([k,v])=>`<span title="剩余${v.duration}次主牌结算">${{burn:'灼热',charge:'储势',antiheal:'禁疗',exposed:'暴露'}[k]||k} ${v.layers}</span>`).join('')}${player.debt.length?`<span>待扣生命 ${player.debt.reduce((n,d)=>n+d.n,0)}</span>`:''}</div></div>`;}
 function tutorial(){return l?`<section class="tutorial lesson-sheet"><div class="lesson-number">${String(lesson+1).padStart(2,'0')} <small>/ ${LESSONS.length}</small></div><h2>${l.title}</h2><p>${l.body}</p><div class="goal">${l.goal}</div>${complete?'<div class="stage-message">✓ 本课操作已完成</div>':''}<div class="actions">${l.info||complete?btn(lesson===LESSONS.length-1?'开始练习对局':'下一课','next','class="primary"'):''}${btn('重做本课','retry')}${btn('课程目录','lessons')}</div></section>`:'';}
 function sidebar(){return `<aside class="table-side">${tutorial()}<details class="table-details" ${l?'':'open'}><summary>结算记录</summary><div class="log" aria-live="polite">${[...s.log].reverse().slice(0,35).map(t=>`<p>${esc(t)}</p>`).join('')}</div></details><details class="table-details"><summary>公开信息与对局存档</summary><p>对方手牌与牌库顺序不公开。</p><div class="actions">${btn('双方公开区域','zones')}${btn('对手完整卡组','opponent-deck')}${btn('导出对局记录','export-match')}</div></details></aside>`;}
 if(s.choice?.then?.mode==='mulligan'){
  const c=s.choice;return `<div class="game-layout"><section class="card-table mulligan-table">${hero(o,1)}<div class="mulligan-title"><span>OPENING HAND</span><h2>先决定留下哪几张。</h2><p>起手5张。点选要换掉的牌，每人只能更换一次。换走的牌会在补牌后洗回牌库。</p></div>${c.owner===0?`<section class="choice mulligan-choice"><h3>开局换牌</h3><p>请选择0—5项，已选${ui.choiceIds.length}。</p><div class="opening-hand">${c.options.map(x=>physicalCard(p.hand.find(e=>e.uid===x.id),{action:'choice',picked:ui.choiceIds.includes(x.id),tag:ui.choiceIds.includes(x.id)?'将更换':''})).join('')}</div>${btn(ui.choiceIds.length?'更换选中的'+ui.choiceIds.length+'张':'全部保留','choose','class="primary play-button"')}<p class="muted">建议至少留一张不需要额外费用的主牌。同名的另一张仍可能被抽到。</p></section>`:'<div class="waiting-response">对手正在选择起手牌……</div>'}${hero(p,0)}</section>${sidebar()}</div>`;
 }
 const result=pending&&sel.number?judge(pending.rule,pending.number,sel.number):null;
 const main=selected(sel.main),support=selected(sel.support),field=selected(sel.field);
 const lastResolved=[...s.log].reverse().find(t=>t.includes('判为'));
 const occupied=new Set([sel.main,sel.support,sel.field,sel.gift,...(sel.materials||[])]);
 return `<div class="game-layout"><section class="card-table">
  <div class="opponent-edge">${hero(o,1)}<div class="opponent-hand" aria-label="对手有${o.hand.length}张隐藏手牌">${Array.from({length:Math.min(8,o.hand.length)},(_,i)=>`<i class="card-back" style="--fan:${(i-(Math.min(8,o.hand.length)-1)/2)*3}deg"><span>◇</span></i>`).join('')}<small>${o.hand.length}张</small></div><div class="round-marker"><b>${s.round}<span>/20</span></b><small>完整回合</small></div></div>
  <div class="table-rules"><div><small>当前判定</small><b>${ruleName(s.rule)}</b><span>${esc(RULES.find(r=>r.id===s.rule).text)}</span></div><div class="upcoming-rule"><small>${3-Math.floor(s.actions/2)%3}回合后</small><b>→ ${ruleName(s.nextRule)}</b></div></div>
  <div class="arena">
   <div class="card-slot pending-slot"><h3>${pending?(pending.owner===0?'你的牌 · 等待回应':'对手的牌 · 等你回应'):'待结算区'}</h3>${pending?physicalCard(pending.card,{face:result,number:pending.number,commit:changed}):`<div class="empty-card"><span>◇</span><p>${s.ended?'本局结算结束':'第一张牌会放在这里，<br>等待下一张牌回应。'}</p></div>`}<small>${pending?`按入场时的「${ruleName(pending.rule)}」判定`:''}</small></div>
   <div class="response-arrow"><span>→</span><small>${result?`对手${result==='success'?'成功':'失败'}`:'回应'}</small></div>
   <div class="card-slot next-slot"><h3>${s.ended?'下次再较量':s.turn===1?'对手正在考虑……':'准备打出的组合'}</h3>${main?physicalCard(main,{number:sel.number,tag:'本次主牌'}):`<div class="empty-card"><span>＋</span><p>${complete?'本课完成，<br>继续右侧下一课。':s.ended?'这局已经结束。':'从下方手牌<br>选一张主牌。'}</p></div>`}<div class="attachments">${support?`<span>辅牌 · ${esc(CARDS[support.cardId].name)}</span>`:''}${field?`<span>条款 · ${esc(CARDS[field.cardId].name)}</span>`:''}</div></div>
  </div>
  ${pending?.support||pending?.field?`<div class="pending-addons">上一张的搭配：${pending.support?`${esc(CARDS[pending.support.cardId].name)} — ${esc(CARDS[pending.support.cardId].text)}`:''}${pending.field?` / ${esc(CARDS[pending.field.cardId].name)}（${pending.fieldFace==='success'?'成功':'失败'}时建立）`:''}</div>`:''}
  ${s.field?`<div class="table-field"><span class="field-symbol">§</span><div><b>${esc(CARDS[s.field.id].name)}</b><small>${esc(CARDS[s.field.id].text)}</small></div>${activeFields.includes(s.field.id)?btn('使用条款','field',interactive&&!s.fieldSpent.action?'':'disabled'):'<span class="automatic-label">双方自动生效</span>'}</div>`:''}
  ${s.ended?`<section class="result table-result"><h2>${s.winner==='draw'?'平局':s.winner===0?'你赢了':'本局落败'}</h2><p>${esc(s.log.at(-1))}</p>${btn('再来一局','start','class="primary"')} ${btn('导出对局记录','export-match')}</section>`:s.choice?choiceUI():`<section class="selection table-controls"><div class="response-preview">${result?`数字 <b>${sel.number}</b> 会让上一张<b class="${result}">${result==='success'?'成功':'失败'}</b>。${esc(CARDS[pending.card.cardId][result])}`:main?'接着选择一个数字，再确认出牌。':'选主牌 → 可加辅牌 / 条款 → 选数字 → 确认。'}<small>${result?'辅牌、状态和公共条款仍会修正牌面效果。':''}</small></div><div class="numbers">${Array.from({length:20},(_,i)=>i+1).map(n=>btn(n,'number',`data-id="${n}" class="number-chip ${sel.number===n?'selected':''}" ${!interactive||p.used.includes(n)?'disabled':''} aria-label="数字${n}${p.used.includes(n)?'，已使用':''}"`)).join('')}</div><div class="play-row"><div class="actions">${btn(cardMode==='material'?'材料模式 ✓':'选费用材料','material',interactive?'':'disabled')}${p.profession==='LU'?btn(cardMode==='gift'?'赠牌模式 ✓':'选赠牌','gift',interactive?'':'disabled'):''}${btn('清空','clear',interactive?'':'disabled')}<small>材料 ${sel.materials?.length||0}张${sel.gift?' · 已选赠牌':''}</small></div>${btn('确认出牌','submit',interactive?'class="primary play-button"':'class="play-button" disabled')}</div>${sel.field?`<label class="inline-setting">这条款在<select data-input="field-face">${options([['success','主牌成功'],['failure','主牌失败']],sel.fieldFace||'success')}</select>时建立</label>`:''}${p.profession==='PR'?`<label class="inline-setting">英雄宣告（剩${3-p.oaths}次）<select data-input="oath">${options([['','不宣告'],['success','成功'],['failure','失败']],sel.oath||'')}</select><small>命中+4甲，落空失去2生命。</small></label>`:''}${p.profession==='LU'&&sel.gift?`<label class="inline-setting">赠牌时机<select data-input="gift-face">${options([['success','成功时'],['failure','失败时']],sel.giftFace||'success')}</select></label>`:''}${s.field?.id==='PR-R5'?btn(sel.openHand?'✓ 将亮出手牌':'亮出手牌换回收','open-hand'):''}</section>`}
  <div class="your-edge">${hero(p,0)}<div class="handtools"><label>你的手牌<select aria-label="筛选手牌" data-input="hand-kind">${options([['','全部'],['main','主牌'],['support','辅牌'],['field','条款']],handKind)}</select></label><small>${cardMode==='material'?'正在选费用材料':cardMode==='gift'?'正在选赠牌':'点选，不会立刻打出'} · ${20-p.used.length}个数字可用</small></div></div>
  <div class="hand-rack">${p.hand.filter(e=>!handKind||CARDS[e.cardId].kind===handKind).map(e=>physicalCard(e,{action:'hand',picked:occupied.has(e.uid),tag:sel.materials?.includes(e.uid)?'费用材料':sel.gift===e.uid?'赠牌':p.emergency===e.uid?'本回合必须打出':''})).join('')}</div>
  <div class="last-exchange">${lastResolved?esc(lastResolved):'双方的牌交替结算。你的新牌不会抢在对方旧牌前生效。'}</div>
 </section>${sidebar()}</div>`;
}
