import fs from 'node:fs/promises';
import {UNITS,CARDS,RULES,PLEDGES,EFFECTS,KEYWORDS,CONTENT} from '../content.js';
const parts=['# 逆誓竞技场 · 完整内容表\n\n由游戏实际数据导出。兵种30、效果牌50、规则50、承诺50。\n\n规则采用25指标的正反方向；效果牌采用26底层效果配对。所有对象ID稳定，可替换美术及调整数值。'];
parts.push('## 兵种');
for(const u of UNITS)parts.push(`### ${u.id} · ${u.name}\n\n人口 ${u.pop}；生命 ${u.hp}；伤害 ${u.atk}；射程 ${u.range}；间隔 ${u.interval}秒；移速 ${u.speed}。\n\n${u.tags.map(t=>KEYWORDS[t]).join('\n\n')}\n\n> ${u.flavor}`);
parts.push('## 双面效果牌');for(const c of CARDS)parts.push(`### ${c.id} · ${c.name}\n\n- 成功：${EFFECTS[c.success].text}。\n- 失败：${EFFECTS[c.failure].text}。`);
parts.push('## 共用规则');for(const r of RULES)parts.push(`### ${r.id} · ${r.name}\n\n${r.description}\n\n关联：${r.counter}。指标：${r.metric}。`);
parts.push('## 公开承诺');for(const p of PLEDGES)parts.push(`### ${p.id} · ${p.name}\n\n${p.description}`);
await fs.writeFile(new URL('../CATALOG.md',import.meta.url),parts.join('\n\n')+'\n');
await fs.writeFile(new URL('../catalog.json',import.meta.url),JSON.stringify({...CONTENT,effects:EFFECTS,keywords:KEYWORDS},null,2));
console.log('Exported 180 entries to CATALOG.md and catalog.json');
